-- Migration: Add more fake example products for neuf listings
-- Timestamp: 20260715130000

DO $$
BEGIN
  INSERT INTO public.products (id, slug, name, brand, category, activity, weight_g, price_eur, stock, image, image_alt, badge, description, featured, stock_statut)
  VALUES
    (gen_random_uuid(), 'salomon-x-ultra-4-gtx', 'X Ultra 4 GTX', 'Salomon', 'Chaussures', ARRAY['Randonnée', 'Trekking'], 960, 149.95, 8, 'https://images.unsplash.com/photo-1573543794198-73ff121c0a8f', 'Chaussures de randonnée imperméables grises et vertes Salomon sur fond blanc', 'Bestseller', 'Chaussures de randonnée polyvalentes avec membrane GORE-TEX. Semelle Contagrip MA pour une adhérence optimale sur tous terrains. Tige basse légère et respirante.', true, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'black-diamond-spot-400', 'Spot 400 Headlamp', 'Black Diamond', 'Éclairage', ARRAY['Randonnée', 'Alpinisme', 'Trail'], 91, 44.95, 15, 'https://images.unsplash.com/photo-1602884347998-8320464ae9cd', 'Lampe frontale noire Black Diamond avec faisceau lumineux dans une forêt de nuit', '', 'Lampe frontale 400 lumens avec technologie PowerTap. Étanche IPX8. Autonomie jusqu''à 200h. Idéale pour le trail et le bivouac.', false, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'patagonia-nano-puff-jacket', 'Nano Puff Jacket', 'Patagonia', 'Vêtements', ARRAY['Randonnée', 'Alpinisme', 'Voyage'], 312, 229.00, 6, 'https://images.unsplash.com/photo-1618143928355-3d9afff6ec23', 'Veste doudoune légère bleue Patagonia portée par un randonneur en montagne', 'Éco', 'Doudoune ultra-légère en PrimaLoft Gold Eco. Isolation synthétique résistante à l''humidité. Compressible dans sa propre poche. Matériaux recyclés.', true, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'msr-pocket-rocket-2', 'PocketRocket 2', 'MSR', 'Cuisine', ARRAY['Randonnée', 'Bivouac', 'Alpinisme'], 73, 49.95, 12, 'https://images.unsplash.com/photo-1662148460486-c8ca9372e13e', 'Réchaud de camping ultra-compact MSR posé sur une casserole en aluminium en plein air', '', 'Réchaud ultra-compact et léger (73g). Ébullition rapide en 3,5 min. Compatible cartouches isobutane. Idéal pour le bivouac solo ou en duo.', false, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'osprey-exos-58', 'Exos 58', 'Osprey', 'Sacs à dos', ARRAY['Randonnée', 'Trekking', 'Trail'], 1420, 269.95, 4, 'https://img.rocket.new/generatedImages/rocket_gen_img_1de5a8766-1772222096368.png', 'Sac à dos de randonnée légère Osprey vert 58L posé sur un rocher en montagne', 'Nouveau', 'Sac à dos ultra-léger 58L avec suspension AirSpeed. Dos ventilé, ceinture lombaire réglable. Housse de pluie intégrée. Idéal pour les treks multi-jours.', true, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'petzl-actik-core', 'Actik Core', 'Petzl', 'Éclairage', ARRAY['Randonnée', 'Bivouac', 'Spéléologie'], 87, 54.95, 20, 'https://images.unsplash.com/photo-1602884347998-8320464ae9cd', 'Lampe frontale rouge Petzl avec batterie rechargeable sur fond blanc', '', 'Lampe frontale rechargeable 450 lumens. Batterie CORE rechargeable via USB. Éclairage rouge pour préserver la vision nocturne. Étanche IPX4.', false, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'nemo-tensor-insulated', 'Tensor Insulated 20R', 'Nemo', 'Couchage', ARRAY['Randonnée', 'Bivouac', 'Alpinisme'], 510, 199.95, 7, 'https://images.unsplash.com/photo-1575270430711-3a5788f712bf', 'Matelas de camping gonflable argenté et orange Nemo déployé dans une tente de bivouac', 'Top vente', 'Matelas gonflable isolé R-value 4.2. Technologie Spaceframe pour un confort optimal. Valve Vortex pour un gonflage rapide. Poids 510g.', true, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'garmin-inreach-mini-2', 'inReach Mini 2', 'Garmin', 'Navigation', ARRAY['Randonnée', 'Alpinisme', 'Expédition'], 100, 399.99, 3, 'https://images.unsplash.com/photo-1697115876539-98f4717cbbc6', 'GPS satellite Garmin orange inReach Mini posé sur une carte topographique', 'Essentiel', 'Communicateur satellite bidirectionnel avec GPS. Envoi de messages SOS. Suivi de position en temps réel. Autonomie 14 jours. Abonnement requis.', true, 'reappro'::stock_statut_type),
    (gen_random_uuid(), 'rab-neutrino-pro-400', 'Neutrino Pro 400', 'Rab', 'Couchage', ARRAY['Alpinisme', 'Expédition', 'Bivouac'], 1050, 449.00, 5, 'https://images.unsplash.com/photo-1722495274040-463c786b09b6', 'Sac de couchage duvet bleu nuit Rab déployé dans une tente avec vue sur les étoiles', '', 'Sac de couchage duvet 800+ cuin. Confort -5°C, limite -12°C. Traitement DWR. Fermeture éclair anti-accrochage. Sac de compression inclus.', false, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'leki-micro-vario-carbon', 'Micro Vario Carbon', 'Leki', 'Bâtons', ARRAY['Randonnée', 'Trail', 'Trekking'], 490, 189.95, 9, 'https://images.unsplash.com/photo-1698778508401-d07840925aeb', 'Bâtons de randonnée pliables en carbone Leki noirs posés sur un sentier de montagne', '', 'Bâtons pliables ultra-légers en carbone (245g/bâton). Poignées liège naturel. Système SpeedLock 2. Longueur réglable 100-130cm.', false, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'hilleberg-nallo-2-gt', 'Nallo 2 GT', 'Hilleberg', 'Tentes', ARRAY['Alpinisme', 'Expédition', 'Bivouac'], 2100, 849.00, 2, 'https://images.unsplash.com/photo-1571364588707-8638d6c49fea', 'Tente quatre saisons rouge Hilleberg installée sur un plateau enneigé en haute montagne', 'Pro', 'Tente 4 saisons 2 places ultra-résistante. Double paroi Kerlon 1200. Arceaux en aluminium DAC. Résiste aux vents violents et à la neige lourde.', true, 'en_stock'::stock_statut_type),
    (gen_random_uuid(), 'katadyn-befree-3l', 'BeFree 3L', 'Katadyn', 'Eau', ARRAY['Randonnée', 'Trekking', 'Survie'], 60, 59.95, 18, 'https://img.rocket.new/generatedImages/rocket_gen_img_1bba8898e-1773112388210.png', 'Filtre à eau portable Katadyn utilisé au bord d''un ruisseau de montagne', '', 'Filtre à eau souple 3L. Filtration 0.1 micron. Débit 2L/min. Élimine bactéries et protozoaires. Léger et compressible. Idéal pour les groupes.', false, 'en_stock'::stock_statut_type)
  ON CONFLICT (slug) DO NOTHING;
EXCEPTION
  WHEN OTHERS THEN
    RAISE NOTICE 'Seed products failed: %', SQLERRM;
END $$;
