#!/usr/bin/env node
/**
 * BUILD SF-STYLE ICON SPRITE
 * ==========================
 * Generates monochrome SVG mask assets (`public/icons/sf/*.svg`) plus the name
 * manifest consumed by the canonical `Icon` primitive, from the MIT-licensed
 * Phosphor asset pack (`@phosphor-icons/core`, a devDependency).
 *
 * No Apple SF Symbols assets are used — the visual language is SF-inspired,
 * not Apple IP. See `scripts/icons/phosphor-map.mjs` for attribution.
 *
 * Usage: node scripts/icons/build-sprite.mjs
 */

import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const setPath = path.join(root, 'scripts', 'icons', 'icon-set.json');
const phosphorDir = path.join(root, 'node_modules', '@phosphor-icons', 'core', 'assets', 'regular');
const outDir = path.join(root, 'public', 'icons', 'sf');
const manifestPath = path.join(root, 'src', 'components', 'ui', 'Icon', 'registry.generated.ts');

if (!fs.existsSync(setPath)) {
  console.error(`✗ Source set introuvable : ${path.relative(root, setPath)}`);
  process.exit(1);
}
if (!fs.existsSync(phosphorDir)) {
  if (fs.existsSync(manifestPath)) {
    console.warn('⚠ @phosphor-icons/core absent mais les glyphes générés existent — étape ignorée.');
    process.exit(0);
  }
  console.error('✗ @phosphor-icons/core introuvable. Exécutez `npm install` (devDependency).');
  process.exit(1);
}

const set = JSON.parse(fs.readFileSync(setPath, 'utf8'));
fs.mkdirSync(outDir, { recursive: true });

const names = [];
const missing = [];

for (const { name, slug } of set) {
  const src = path.join(phosphorDir, `${slug}.svg`);
  if (!fs.existsSync(src)) {
    missing.push(`${name} (${slug})`);
    continue;
  }
  let svg = fs.readFileSync(src, 'utf8').trim();
  svg = svg.replace(/fill="currentColor"/g, 'fill="#000"');
  svg = svg.replace(/\s+$/g, '');
  fs.writeFileSync(path.join(outDir, `${name}.svg`), svg + '\n');
  names.push(name);
}

names.sort();

const manifest = `// AUTO-GENERATED by scripts/icons/build-sprite.mjs — do not edit by hand.
// SF-inspired monochrome glyphs derived from MIT-licensed Phosphor Icons.
/* eslint-disable */
export const SVG_MASK_ICON_NAMES = new Set<string>([
${names.map((n) => `  '${n}',`).join('\n')}
]);
`;

fs.writeFileSync(manifestPath, manifest);

console.log(`✓ ${names.length} glyphes SF-style générés dans public/icons/sf/`);
console.log(`✓ Manifest : ${path.relative(root, manifestPath)}`);
if (missing.length > 0) {
  console.warn(`⚠ ${missing.length} glyphe(s) introuvable(s) : ${missing.join(', ')}`);
  process.exit(1);
}
