/**
 * Lucide → Phosphor slug overrides.
 *
 * Used by `scripts/icons/build-sprite.mjs` (build-time only) to translate the
 * Lucide icon names still used across the codebase into MIT-licensed Phosphor
 * glyphs. Names not present here fall back to a direct kebab-case match.
 */
export const LUCIDE_TO_PHOSPHOR = {
  AlertCircle: 'warning-circle',
  AlertTriangle: 'warning',
  ArchiveRestore: 'archive',
  ArrowRightLeft: 'arrows-left-right',
  Award: 'medal',
  Banknote: 'money',
  Battery: 'battery-full',
  BedDouble: 'bed',
  BellOff: 'bell-slash',
  BellRing: 'bell-ringing',
  Bike: 'bicycle',
  Building2: 'buildings',
  CalendarDays: 'calendar-dots',
  CheckCheck: 'checks',
  CheckCircle2: 'check-circle',
  ChevronDown: 'caret-down',
  ChevronLeft: 'caret-left',
  ChevronRight: 'caret-right',
  ChevronsUpDown: 'caret-up-down',
  ChevronUp: 'caret-up',
  ClipboardList: 'clipboard-text',
  CloudDrizzle: 'cloud-rain',
  CloudOff: 'cloud-slash',
  CloudRainWind: 'cloud-rain',
  Droplet: 'drop',
  Droplets: 'drop-half',
  Edit2: 'pencil-simple',
  Edit3: 'pencil-simple',
  Ellipsis: 'dots-three',
  Euro: 'currency-eur',
  ExternalLink: 'arrow-square-out',
  EyeOff: 'eye-slash',
  FileCheck: 'file',
  Filter: 'funnel',
  FlaskConical: 'flask',
  GripVertical: 'dots-six-vertical',
  HeartPulse: 'pulse',
  HelpCircle: 'question',
  Home: 'house',
  ImageOff: 'image-broken',
  ImagePlus: 'image-square',
  KeyRound: 'key',
  Layers: 'stack',
  LogOut: 'sign-out',
  Mail: 'envelope',
  MailPlus: 'envelope',
  Map: 'map-trifold',
  MessageSquare: 'chat',
  MessageSquarePlus: 'chat-circle-dots',
  Mic: 'microphone',
  MoonStar: 'moon-stars',
  MoreHorizontal: 'dots-three',
  MoreVertical: 'dots-three-vertical',
  Mountain: 'mountains',
  Navigation: 'navigation-arrow',
  Pin: 'push-pin',
  Plane: 'airplane',
  RefreshCw: 'arrows-clockwise',
  Reply: 'arrow-bend-up-left',
  RotateCcw: 'arrow-counter-clockwise',
  Route: 'path',
  Scale: 'scales',
  Search: 'magnifying-glass',
  Send: 'paper-plane-tilt',
  Share2: 'share-network',
  ShieldAlert: 'shield-warning',
  Ship: 'boat',
  Shirt: 't-shirt',
  Smile: 'smiley',
  Sparkles: 'sparkle',
  Sunrise: 'sun-horizon',
  Sunset: 'sun-horizon',
  Trash2: 'trash',
  TrendingDown: 'trend-down',
  TrendingUp: 'trend-up',
  Unlock: 'lock-open',
  Weight: 'barbell',
  Wifi: 'wifi-high',
  WifiOff: 'wifi-slash',
  Zap: 'lightning',
};
