export const POPULAR_KITS = [
  {
    name: 'Kit Islande',
    slug: 'islande-automne',
    tag: 'TREK · AUTOMNE',
    items: 32,
    weight: '8,4 kg',
    price: '1 240 €',
    trust: 94,
    color: '#2A4A5E',
    emoji: '🏔️',
    desc: 'Volcans, geysers, aurores boréales',
  },
  {
    name: 'Kit Japon',
    slug: 'japon-printemps',
    tag: 'URBAIN · CULTURE',
    items: 28,
    weight: '6,2 kg',
    price: '890 €',
    trust: 97,
    color: '#4A2A3A',
    emoji: '🌸',
    desc: 'Temples, cerisiers, mégapoles',
  },
  {
    name: 'Kit Tour du Monde',
    slug: 'tour-du-monde',
    tag: 'LONG COURS · MULTI',
    items: 48,
    weight: '11,8 kg',
    price: '2 100 €',
    trust: 91,
    color: '#2A3A2A',
    emoji: '🌍',
    desc: 'Tous les continents, toutes les saisons',
  },
  {
    name: 'Kit Vanlife',
    slug: 'vanlife-europe',
    tag: 'ROAD TRIP · LIBERTÉ',
    items: 38,
    weight: '14,2 kg',
    price: '1 680 €',
    trust: 89,
    color: '#3A3A2A',
    emoji: '🚐',
    desc: 'Routes, bivouacs, liberté totale',
  },
  {
    name: 'Kit GR20',
    slug: 'gr20-corse',
    tag: 'RANDONNÉE · EXTRÊME',
    items: 24,
    weight: '7,1 kg',
    price: '780 €',
    trust: 96,
    color: '#2A3A4A',
    emoji: '⛰️',
    desc: "Le sentier le plus difficile d'Europe",
  },
  {
    name: 'Kit Digital Nomad',
    slug: 'digital-nomad',
    tag: 'TRAVAIL · MOBILITÉ',
    items: 22,
    weight: '5,4 kg',
    price: '1 120 €',
    trust: 93,
    color: '#3A2A4A',
    emoji: '💻',
    desc: "Travailler depuis n\'importe où",
  },
];
