// AUTO-GENERATED by scripts/icons/build-heroicons-map.mjs — do not edit by hand.
//
// Imports nommés des seules icônes Heroicons que l'app résout réellement.
// Remplace l'ancien `import * as HeroIcons from '@heroicons/react/24/outline'`
// (648 modules, non élagables car utilisés comme table de correspondance à
// l'exécution) : le reste du jeu disparaît du bundle.
/* eslint-disable */
import type React from 'react';

import {
  AdjustmentsHorizontalIcon,
  BoltIcon,
  BriefcaseIcon,
  BuildingOfficeIcon,
  ChartBarIcon,
  DocumentChartBarIcon,
  EyeIcon,
  EyeSlashIcon,
  FlagIcon,
  HandThumbUpIcon,
  KeyIcon,
  NoSymbolIcon,
  PrinterIcon,
  RectangleStackIcon,
  StarIcon,
  TrophyIcon,
  TruckIcon,
} from '@heroicons/react/24/outline';

import {
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconSolid,
  BoltIcon as BoltIconSolid,
  BriefcaseIcon as BriefcaseIconSolid,
  BuildingOfficeIcon as BuildingOfficeIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  DocumentChartBarIcon as DocumentChartBarIconSolid,
  EyeIcon as EyeIconSolid,
  EyeSlashIcon as EyeSlashIconSolid,
  FlagIcon as FlagIconSolid,
  HandThumbUpIcon as HandThumbUpIconSolid,
  KeyIcon as KeyIconSolid,
  NoSymbolIcon as NoSymbolIconSolid,
  PrinterIcon as PrinterIconSolid,
  RectangleStackIcon as RectangleStackIconSolid,
  StarIcon as StarIconSolid,
  TrophyIcon as TrophyIconSolid,
  TruckIcon as TruckIconSolid,
} from '@heroicons/react/24/solid';

/** Icônes Heroicons résolvables, par variante. Table statique : fully élaguable. */
export const HERO_OUTLINE: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  AdjustmentsHorizontalIcon,
  BoltIcon,
  BriefcaseIcon,
  BuildingOfficeIcon,
  ChartBarIcon,
  DocumentChartBarIcon,
  EyeIcon,
  EyeSlashIcon,
  FlagIcon,
  HandThumbUpIcon,
  KeyIcon,
  NoSymbolIcon,
  PrinterIcon,
  RectangleStackIcon,
  StarIcon,
  TrophyIcon,
  TruckIcon,
};

export const HERO_SOLID: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  AdjustmentsHorizontalIcon: AdjustmentsHorizontalIconSolid,
  BoltIcon: BoltIconSolid,
  BriefcaseIcon: BriefcaseIconSolid,
  BuildingOfficeIcon: BuildingOfficeIconSolid,
  ChartBarIcon: ChartBarIconSolid,
  DocumentChartBarIcon: DocumentChartBarIconSolid,
  EyeIcon: EyeIconSolid,
  EyeSlashIcon: EyeSlashIconSolid,
  FlagIcon: FlagIconSolid,
  HandThumbUpIcon: HandThumbUpIconSolid,
  KeyIcon: KeyIconSolid,
  NoSymbolIcon: NoSymbolIconSolid,
  PrinterIcon: PrinterIconSolid,
  RectangleStackIcon: RectangleStackIconSolid,
  StarIcon: StarIconSolid,
  TrophyIcon: TrophyIconSolid,
  TruckIcon: TruckIconSolid,
};
