import { MetadataRoute } from 'next';

const base = process.env.NEXT_PUBLIC_SITE_URL || 'https://lekitduvoyageur.fr';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        // Googlebot: explicit allow for SEO-priority pages
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/pays/',
          '/produit/',
          '/boutique/',
          '/catalogue/',
          '/kits/',
          '/guides/',
          '/experts/',
          '/communaute/',
          '/explorer/',
          '/avis/',
          '/outils/',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/checkout/',
          '/panier/',
          '/compte/',
          '/messagerie/',
          '/groupe/',
          '/groupes/',
          '/inventaire/',
          '/connexion/',
          '/inscription/',
          '/auth/',
          '/profil/',
          '/carnets/',
          '/mon-kit/',
          '/mes-aventures/',
          '/rapport-expedition/',
          '/rapport-kit/',
        ],
        crawlDelay: 0,
      },
      {
        // Bingbot: similar rules
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/pays/',
          '/produit/',
          '/boutique/',
          '/catalogue/',
          '/kits/',
          '/guides/',
          '/experts/',
          '/communaute/',
          '/explorer/',
          '/avis/',
          '/outils/',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/checkout/',
          '/panier/',
          '/compte/',
          '/messagerie/',
          '/groupe/',
          '/groupes/',
          '/inventaire/',
          '/connexion/',
          '/inscription/',
          '/auth/',
          '/profil/',
          '/carnets/',
          '/mon-kit/',
          '/mes-aventures/',
          '/rapport-expedition/',
          '/rapport-kit/',
        ],
        crawlDelay: 1,
      },
      {
        // All other crawlers
        userAgent: '*',
        allow: [
          '/',
          '/pays/',
          '/produit/',
          '/boutique/',
          '/catalogue/',
          '/kits/',
          '/guides/',
          '/experts/',
          '/communaute/',
          '/explorer/',
          '/avis/',
          '/outils/',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/checkout/',
          '/panier/',
          '/compte/',
          '/messagerie/',
          '/groupe/',
          '/groupes/',
          '/inventaire/',
          '/connexion/',
          '/inscription/',
          '/auth/',
          '/profil/',
          '/carnets/',
          '/mon-kit/',
          '/mes-aventures/',
          '/rapport-expedition/',
          '/rapport-kit/',
        ],
        crawlDelay: 2,
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}