import { MetadataRoute } from 'next';

const base = process.env.NEXT_PUBLIC_SITE_URL || 'https://lekitduvoyageur.fr';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/pays/',
          '/produit/',
          '/boutique/',
          '/kits/',
          '/guides/',
          '/experts/',
          '/communaute/',
          '/explorer/',
          '/avis/',
          '/outils/',
          '/blog/',
          '/carte-interactive/',
          '/abonnements/',
          '/pro/',
          '/ambassadeurs/',
          '/createurs/',
          '/evenements/',
          '/encheres/',
          '/location/',
          '/occasion/',
          '/faq/',
          '/contact/',
          '/carbone/',
          '/ai-configurator/',
          '/naviguer/',
          '/carnets/',
          '/cookies/',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/checkout/',
          '/panier/',
          '/compte/',
          '/messagerie/',
          '/groupes/',
          '/inventaire/',
          '/connexion/',
          '/inscription/',
          '/auth/',
          '/profil/',
          '/mon-kit/',
          '/mes-aventures/',
          '/rapport-expedition/',
          '/rapport-kit/',
          '/copilote/',
          '/voyage-ia/',
          '/feed/',
          '/recommandations/',
          '/publier/',
          '/nouveau-groupe/',
          '/gamification/',
          '/alertes/',
          '/activite/',
          '/jumeau-3d/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/pays/',
          '/produit/',
          '/boutique/',
          '/kits/',
          '/guides/',
          '/experts/',
          '/communaute/',
          '/explorer/',
          '/avis/',
          '/outils/',
          '/blog/',
          '/carte-interactive/',
          '/abonnements/',
          '/pro/',
          '/ambassadeurs/',
          '/createurs/',
          '/evenements/',
          '/encheres/',
          '/location/',
          '/occasion/',
          '/faq/',
          '/contact/',
          '/carbone/',
          '/ai-configurator/',
          '/naviguer/',
          '/carnets/',
          '/cookies/',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/checkout/',
          '/panier/',
          '/compte/',
          '/messagerie/',
          '/groupes/',
          '/inventaire/',
          '/connexion/',
          '/inscription/',
          '/auth/',
          '/profil/',
          '/mon-kit/',
          '/mes-aventures/',
          '/rapport-expedition/',
          '/rapport-kit/',
          '/copilote/',
          '/voyage-ia/',
          '/feed/',
          '/recommandations/',
          '/publier/',
          '/nouveau-groupe/',
          '/gamification/',
          '/alertes/',
          '/activite/',
          '/jumeau-3d/',
        ],
      },
      {
        userAgent: 'GPTBot',
        disallow: '/',
      },
      {
        userAgent: 'ClaudeBot',
        disallow: '/',
      },
      {
        userAgent: 'Google-Extended',
        disallow: '/',
      },
      {
        userAgent: 'Bytespider',
        disallow: '/',
      },
      {
        userAgent: 'CCBot',
        disallow: '/',
      },
      {
        userAgent: 'PerplexityBot',
        disallow: '/',
      },
      {
        userAgent: '*',
        allow: [
          '/',
          '/pays/',
          '/produit/',
          '/boutique/',
          '/kits/',
          '/guides/',
          '/experts/',
          '/communaute/',
          '/explorer/',
          '/avis/',
          '/outils/',
          '/blog/',
          '/carte-interactive/',
          '/abonnements/',
          '/pro/',
          '/ambassadeurs/',
          '/createurs/',
          '/evenements/',
          '/encheres/',
          '/location/',
          '/occasion/',
          '/faq/',
          '/contact/',
          '/carbone/',
          '/ai-configurator/',
          '/naviguer/',
          '/carnets/',
          '/cookies/',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/checkout/',
          '/panier/',
          '/compte/',
          '/messagerie/',
          '/groupes/',
          '/inventaire/',
          '/connexion/',
          '/inscription/',
          '/auth/',
          '/profil/',
          '/mon-kit/',
          '/mes-aventures/',
          '/rapport-expedition/',
          '/rapport-kit/',
          '/copilote/',
          '/voyage-ia/',
          '/feed/',
          '/recommandations/',
          '/publier/',
          '/nouveau-groupe/',
          '/gamification/',
          '/alertes/',
          '/activite/',
          '/jumeau-3d/',
        ],
      },
    ],
    sitemap: `${base}/sitemap.xml`,
  };
}
