/**
 * LKDV — SmartDepartureEngine (Moteur Intelligent de Préparation de Sortie)
 * Unifie : Contexte Randonnée ↔ Matériel Possédé ↔ Kits Existants ↔ Consommables ↔ Météo.
 * Objectif : « Je n'ai presque rien à faire, LKDV a déjà pensé à tout. »
 */

import { UserEquipmentItem } from '@/hooks/useEquipment';
import { CustomKit } from '@/hooks/useUserKits';
import { WeatherSnapshot } from '@/features/hiking/types';
import { createClient } from '@/lib/supabase/client';

export interface DepartureHikeContext {
  id?: string;
  name: string;
  distanceKm: number;
  durationHours?: number;
  elevationGain?: number;
  elevationLoss?: number;
  difficulty?: 'Facile' | 'Moyen' | 'Difficile' | 'Expert' | string;
  season?: 'Printemps' | 'Été' | 'Automne' | 'Hiver' | string;
  terrain?: string;
  hasWaterPoints?: boolean;
  waterPointsCount?: number;
  hasRefuges?: boolean;
  isOvernight?: boolean;
  nightsCount?: number;
  weather?: WeatherSnapshot | null;
  startDate?: string;
}

export interface ConsumablesEstimate {
  waterLiters: number;
  waterReason: string;
  foodMealsCount: number;
  snacksCount: number;
  fuelGrams: number;
  electrolytesRecommended: boolean;
  sunProtectionNeeded: boolean;
  warmLayerNeeded: boolean;
  rainProtectionNeeded: boolean;
}

export interface DepartureChecklistItem {
  id: string;
  name: string;
  category: string;
  weightG: number;
  isOwned: boolean;
  ownedGearId?: string;
  isEssential: boolean;
  status: 'ready' | 'missing' | 'warning' | 'consumable';
  warningMessage?: string;
  actionHint?: string;
}

export interface DeparturePreparationPlan {
  hikeContext: DepartureHikeContext;
  selectedKit: CustomKit | null;
  isAutoGeneratedKit: boolean;
  suitabilityScore: number; // 0 à 100
  totalPackWeightG: number;
  consumables: ConsumablesEstimate;
  checklist: {
    inPackReady: DepartureChecklistItem[];
    consumablesToPack: DepartureChecklistItem[];
    securityChecks: DepartureChecklistItem[];
    missingItems: DepartureChecklistItem[];
  };
  weatherSummary: {
    tempMinMax: string;
    condition: string;
    rainRiskPct: number;
    windKmh: number;
    advice: string;
  };
}

/**
 * 1. Calcul précis des consommables selon durée, dénivelé et météo
 */
export function calculateHikeConsumables(context: DepartureHikeContext): ConsumablesEstimate {
  const duration = context.durationHours || Math.max(1, Math.round((context.distanceKm / 3.8) * 10) / 10);
  const elevation = context.elevationGain || 0;
  const temp = context.weather?.tempC ?? 18;
  const rainRisk = (context.weather?.precipitationProbability ?? 0) * 100;

  // Calcul Eau
  let water = duration * 0.5; // 0.5L par heure standard
  if (elevation > 600) water += 0.5;
  if (elevation > 1200) water += 0.5;
  if (temp > 24) water += duration * 0.25;
  if (temp > 30) water += duration * 0.35;

  // Si des points d'eau sont attestés sur le sentier
  const hasRefills = context.hasWaterPoints || (context.waterPointsCount && context.waterPointsCount > 0);
  if (hasRefills && water > 2.0) {
    water = Math.max(1.5, water * 0.65); // Allègement du sac grâce aux sources identifiées
  }
  water = Math.round(water * 10) / 10;

  // Vivres & Snacks
  const meals = context.isOvernight
    ? (context.nightsCount || 1) * 2 + 1
    : duration >= 5 ? 1 : 0;
  const snacks = Math.max(1, Math.floor(duration / 2.5));

  // Gaz / Réchaud
  const fuel = meals > 0 ? meals * 15 + 10 : 0;

  return {
    waterLiters: Math.max(1.0, water),
    waterReason: hasRefills
      ? `${water}L conseillés (points d'eau disponibles pour ravitailler)`
      : `${water}L nécessaires (aucun point d'eau identifié)`,
    foodMealsCount: meals,
    snacksCount: snacks,
    fuelGrams: fuel,
    electrolytesRecommended: duration > 4 || temp > 25,
    sunProtectionNeeded: temp > 20 || (context.weather?.uvIndex ?? 0) > 4,
    warmLayerNeeded: temp < 12 || elevation > 1500,
    rainProtectionNeeded: rainRisk > 25 || (context.weather?.isAlert ?? false),
  };
}

/**
 * 2. Trouve le kit le plus adapté ou génère un kit sur-mesure automatique
 */
export function resolveDeparturePlan(
  context: DepartureHikeContext,
  userKits: CustomKit[],
  userGear: UserEquipmentItem[]
): DeparturePreparationPlan {
  const duration = context.durationHours || Math.max(1, Math.round((context.distanceKm / 3.8) * 10) / 10);
  const consumables = calculateHikeConsumables(context);
  const isBivouac = context.isOvernight && !context.hasRefuges;

  // Évaluation des kits existants
  let bestKit: CustomKit | null = null;
  let bestScore = 0;

  for (const kit of userKits.filter((k) => k.status === 'active')) {
    let score = 50; // base score

    // Matching d'activité / destination
    if (kit.activity.toLowerCase() === (context.difficulty || '').toLowerCase()) score += 15;
    if (kit.for_destination && context.name.toLowerCase().includes(kit.for_destination.toLowerCase())) score += 20;

    // Matching sac de couchage / tente si nuitée
    const hasShelter = kit.items.some((i) => i.category.toLowerCase().includes('couchage') || i.category.toLowerCase().includes('bivouac'));
    if (isBivouac && hasShelter) score += 25;
    if (!context.isOvernight && !hasShelter) score += 15;

    // Matching pluie / météo
    const hasRainGear = kit.items.some((i) => i.item_name.toLowerCase().includes('pluie') || i.item_name.toLowerCase().includes('veste'));
    if (consumables.rainProtectionNeeded && hasRainGear) score += 10;

    if (score > bestScore) {
      bestScore = score;
      bestKit = kit;
    }
  }

  const isAutoGenerated = bestScore < 65 || !bestKit;

  // Création de la liste des items
  const inPackReady: DepartureChecklistItem[] = [];
  const consumablesToPack: DepartureChecklistItem[] = [];
  const securityChecks: DepartureChecklistItem[] = [];
  const missingItems: DepartureChecklistItem[] = [];

  // ── A. Matériel dans le sac ──
  const gearToUse = isAutoGenerated
    ? userGear.filter((g) => g.condition !== 'à_remplacer')
    : (bestKit?.items || []).map((kitItem) => {
        const matching = userGear.find((g) => g.id === kitItem.gear_item_id) ||
                         userGear.find((g) => g.name.toLowerCase() === kitItem.item_name.toLowerCase());
        return matching || {
          id: kitItem.id,
          name: kitItem.item_name,
          category: kitItem.category,
          weight_g: kitItem.weight_g,
          condition: 'bon' as const,
          user_id: '',
        };
      });

  gearToUse.forEach((gear) => {
    const isLent = (gear as UserEquipmentItem).loan_status === 'prêté';
    const needsMaint = (gear as UserEquipmentItem).next_maintenance_date &&
                       new Date((gear as UserEquipmentItem).next_maintenance_date!).getTime() < Date.now();

    if (isLent) {
      securityChecks.push({
        id: `lent-${gear.id}`,
        name: gear.name,
        category: gear.category,
        weightG: gear.weight_g || 0,
        isOwned: true,
        ownedGearId: gear.id,
        isEssential: true,
        status: 'warning',
        warningMessage: `Prêté à ${(gear as UserEquipmentItem).loan_to_name || 'un ami'}`,
        actionHint: 'Récupérer ou remplacer',
      });
    } else {
      inPackReady.push({
        id: gear.id,
        name: gear.name,
        category: gear.category,
        weightG: gear.weight_g || 0,
        isOwned: true,
        ownedGearId: gear.id,
        isEssential: true,
        status: 'ready',
        warningMessage: needsMaint ? 'Entretien préventif recommandé' : undefined,
      });
    }
  });

  // ── B. Consommables ──
  consumablesToPack.push({
    id: 'cons-water',
    name: `Eau potable (${consumables.waterLiters} L)`,
    category: 'Hydratation',
    weightG: Math.round(consumables.waterLiters * 1000),
    isOwned: true,
    isEssential: true,
    status: 'consumable',
    actionHint: consumables.waterReason,
  });

  if (consumables.foodMealsCount > 0) {
    consumablesToPack.push({
      id: 'cons-meals',
      name: `${consumables.foodMealsCount} repas de randonnée`,
      category: 'Alimentation',
      weightG: consumables.foodMealsCount * 180,
      isOwned: true,
      isEssential: true,
      status: 'consumable',
    });
  }

  consumablesToPack.push({
    id: 'cons-snacks',
    name: `${consumables.snacksCount} en-cas énergétiques`,
    category: 'Alimentation',
    weightG: consumables.snacksCount * 45,
    isOwned: true,
    isEssential: true,
    status: 'consumable',
  });

  if (consumables.fuelGrams > 0) {
    consumablesToPack.push({
      id: 'cons-fuel',
      name: `Cartouche de gaz (${consumables.fuelGrams} g)`,
      category: 'Cuisine',
      weightG: consumables.fuelGrams + 100,
      isOwned: true,
      isEssential: false,
      status: 'consumable',
    });
  }

  // ── C. Sécurité & Météo ──
  if (consumables.rainProtectionNeeded) {
    const hasRain = inPackReady.some((i) => i.name.toLowerCase().includes('pluie') || i.name.toLowerCase().includes('veste'));
    if (!hasRain) {
      missingItems.push({
        id: 'req-rain',
        name: 'Veste imperméable / Coupe-vent',
        category: 'Vêtements',
        weightG: 320,
        isOwned: false,
        isEssential: true,
        status: 'missing',
        actionHint: 'Risque de pluie ou vent détecté',
      });
    }
  }

  if (consumables.warmLayerNeeded) {
    const hasWarm = inPackReady.some((i) => i.name.toLowerCase().includes('doudoune') || i.name.toLowerCase().includes('polaire'));
    if (!hasWarm) {
      missingItems.push({
        id: 'req-warm',
        name: 'Couche thermique (Polaire / Doudoune)',
        category: 'Vêtements',
        weightG: 280,
        isOwned: false,
        isEssential: true,
        status: 'missing',
        actionHint: 'Températures fraîches en altitude',
      });
    }
  }

  // Lampe frontale indispensable si > 4h ou nuit
  if (duration >= 4 || context.isOvernight) {
    const hasLamp = inPackReady.some((i) => i.category.toLowerCase().includes('éclairage') || i.name.toLowerCase().includes('frontale'));
    if (!hasLamp) {
      securityChecks.push({
        id: 'sec-lamp',
        name: 'Lampe frontale chargée',
        category: 'Sécurité',
        weightG: 85,
        isOwned: false,
        isEssential: true,
        status: 'warning',
        actionHint: 'Indispensable pour fin de parcours ou nuit',
      });
    }
  }

  // Trousse de premiers secours
  const hasFirstAid = inPackReady.some((i) => i.category.toLowerCase().includes('sécurité') || i.name.toLowerCase().includes('secours') || i.name.toLowerCase().includes('soin'));
  if (!hasFirstAid) {
    securityChecks.push({
      id: 'sec-firstaid',
      name: 'Trousse de secours & couverture de survie',
      category: 'Sécurité',
      weightG: 150,
      isOwned: false,
      isEssential: true,
      status: 'warning',
      actionHint: 'Fond de sac de sécurité obligatoire',
    });
  }

  // Poids total mesuré
  const totalWeight = inPackReady.reduce((s, i) => s + i.weightG, 0) +
                      consumablesToPack.reduce((s, i) => s + i.weightG, 0);

  // Synthèse Météo
  const temp = context.weather?.tempC ?? 18;
  const weatherSummary = {
    tempMinMax: `${Math.round(temp - 3)}°C — ${Math.round(temp + 2)}°C`,
    condition: context.weather?.condition || (consumables.rainProtectionNeeded ? 'Risque d\'averses' : 'Conditions dégagées'),
    rainRiskPct: Math.round((context.weather?.precipitationProbability ?? 0) * 100),
    windKmh: Math.round(context.weather?.windKmH ?? 15),
    advice: consumables.rainProtectionNeeded
      ? 'Prévoyez votre veste imperméable en haut de sac.'
      : consumables.warmLayerNeeded
      ? 'Températures fraîches : couche isolante recommandée.'
      : 'Excellentes conditions prévues pour votre sortie.',
  };

  return {
    hikeContext: context,
    selectedKit: bestKit,
    isAutoGeneratedKit: isAutoGenerated,
    suitabilityScore: Math.min(100, isAutoGenerated ? 88 : bestScore),
    totalPackWeightG: totalWeight,
    consumables,
    checklist: {
      inPackReady,
      consumablesToPack,
      securityChecks,
      missingItems,
    },
    weatherSummary,
  };
}

/**
 * 3. Enregistrement automatique de fin de randonnée pour mettre à jour l'usage du matériel
 */
export async function recordPostHikeGearUsage(gearIds: string[]) {
  if (!gearIds || gearIds.length === 0) return;
  try {
    const supabase = createClient();
    await supabase.rpc('record_hike_gear_usage', { p_gear_ids: gearIds });
  } catch (err) {
    console.warn('[recordPostHikeGearUsage] Error updating gear usage:', err);
  }
}
