/**
 * LKDV — SmartDepartureEngine (Moteur Intelligent de Préparation de Sortie)
 * Unifie : Contexte Randonnée ↔ Matériel Possédé ↔ Kits Existants ↔ Consommables ↔ Météo.
 * Objectif : « Je n'ai presque rien à faire, LKDV a déjà pensé à tout. »
 */

import { UserEquipmentItem } from '@/hooks/useEquipment';
import { CustomKit } from '@/hooks/useUserKits';
import { WeatherSnapshot } from '@/features/hiking/types';
import { createClient } from '@/lib/supabase/client';

export interface DepartureHikeContext {
  id?: string;
  name: string;
  distanceKm: number;
  durationHours?: number;
  elevationGain?: number;
  elevationLoss?: number;
  difficulty?: 'Facile' | 'Moyen' | 'Difficile' | 'Expert' | string;
  season?: 'Printemps' | 'Été' | 'Automne' | 'Hiver' | string;
  terrain?: string;
  hasWaterPoints?: boolean;
  waterPointsCount?: number;
  hasRefuges?: boolean;
  isOvernight?: boolean;
  nightsCount?: number;
  weather?: WeatherSnapshot | null;
  startDate?: string;
}

export interface ConsumablesEstimate {
  waterLiters: number;
  waterReason: string;
  foodMealsCount: number;
  snacksCount: number;
  fuelGrams: number;
  electrolytesRecommended: boolean;
  sunProtectionNeeded: boolean;
  warmLayerNeeded: boolean;
  rainProtectionNeeded: boolean;
}

export interface DepartureChecklistItem {
  id: string;
  name: string;
  category: string;
  weightG: number;
  isOwned: boolean;
  ownedGearId?: string;
  isEssential: boolean;
  status: 'ready' | 'missing' | 'warning' | 'consumable';
  warningMessage?: string;
  actionHint?: string;
}

export interface DeparturePreparationPlan {
  hikeContext: DepartureHikeContext;
  selectedKit: CustomKit | null;
  isAutoGeneratedKit: boolean;
  suitabilityScore: number; // 0 à 100
  totalPackWeightG: number;
  consumables: ConsumablesEstimate;
  checklist: {
    inPackReady: DepartureChecklistItem[];
    consumablesToPack: DepartureChecklistItem[];
    securityChecks: DepartureChecklistItem[];
    missingItems: DepartureChecklistItem[];
  };
  /**
   * Ce que le fournisseur a réellement relevé, ou `null`.
   *
   * Aucun de ces champs ne porte de repli : une température absente reste
   * absente. C'est ce qui permet à l'écran d'écrire « non mesuré » au lieu
   * d'afficher un nombre plausible.
   */
  weatherSummary: {
    /**
     * La temperature MESUREE, telle quelle, ou `null`.
     *
     * C est le seul nombre que `WeatherSnapshot` autorise : le fournisseur
     * donne une temperature INSTANTANEE, pas une amplitude. Un ecran qui
     * veut la temperature lit ce champ.
     */
    tempC: number | null;
    /**
     * La fourchette min/max du jour, ou `null`.
     *
     * Elle reste `null` tant qu'aucun fournisseur ne rend un MIN et un MAX
     * REELS, et c est le cas aujourd'hui. L'ancienne version sortait la
     * mesure MOINS TROIS et PLUS DEUX, deux nombres ecrits en dur qui
     * donnaient a une temperature ponctuelle l'apparence d'une amplitude
     * relevee. C'est la meme famille qu'un repli chiffre sur une mesure :
     * un nombre plausible affiche la ou il faudrait dire « a verifier ».
     */
    tempMinMax: string | null;
    condition: string | null;
    rainRiskPct: number | null;
    windKmh: number | null;
    /** Faux = personne n'a relevé cette sortie. */
    measured: boolean;
    advice: string;
  };
}

/**
 * 1. Calcul précis des consommables selon durée, dénivelé et météo
 */
export function calculateHikeConsumables(context: DepartureHikeContext): ConsumablesEstimate {
  // Une durée absente est ESTIMÉE, et c'est annoncé comme tel : une
  // estimation d'allure est un calcul, pas une mesure d'une grandeur météo.
  const duration = context.durationHours || Math.max(1, Math.round((context.distanceKm / 3.8) * 10) / 10);
  // Le dénivelé absent vaut 0 ici sans fabriquer de nombre affiché : son seul
  // usage est la comparaison `> 600` plus bas, ou 0 et « inconnu » donnent
  // le même résultat. Aucune surface ne montre cette valeur.
  const elevation = context.elevationGain || 0;
  // Les trois mesures ci-dessous restent `null` quand personne n'a relevé.
  // `null` se compare mal : `null < 12` vaut `true` en JavaScript, donc
  // chaque seuil passe par un garde explicite plutôt que par `??`.
  const temp = context.weather?.tempC ?? null;
  const uv = context.weather?.uvIndex ?? null;
  const rawRain = context.weather?.precipitationProbability ?? null;
  const rainRisk = rawRain === null
    ? null
    : rawRain > 1
      ? Math.min(100, Math.round(rawRain))
      : Math.min(100, Math.round(rawRain * 100));

  // Calcul Eau : plafonné à la capacité physique d'un sac (1.5L à 3.0L max porté)
  let water = duration * 0.45;
  if (elevation > 600) water += 0.4;
  if (temp !== null && temp > 24) water += 0.5;

  const hasRefills = context.hasWaterPoints || (context.waterPointsCount && context.waterPointsCount > 0);
  if (hasRefills) {
    water = Math.min(2.0, Math.max(1.0, water * 0.5));
  } else {
    water = Math.min(3.0, Math.max(1.2, water));
  }
  water = Math.round(water * 10) / 10;

  // Vivres & Snacks
  const meals = context.isOvernight
    ? (context.nightsCount || 1) * 2 + 1
    : duration >= 5 ? 1 : 0;
  const snacks = Math.min(6, Math.max(1, Math.floor(duration / 2.5)));

  // Gaz / Réchaud
  const fuel = meals > 0 ? meals * 15 + 10 : 0;

  return {
    waterLiters: water,
    waterReason: hasRefills
      ? `${water}L dans le sac (points d'eau sur le parcours pour recharger)`
      : `${water}L emportés en autonomie complète`,
    foodMealsCount: meals,
    snacksCount: snacks,
    fuelGrams: fuel,
    electrolytesRecommended: duration > 4 || (temp !== null && temp > 25),
    // Sans UV mesure, la protection solaire ne peut pas se déduire du vide :
    // un indice à zéro transformerait « inconnu » en « indice nul ».
    sunProtectionNeeded: (temp !== null && temp > 20) || (uv !== null && uv > 4),
    warmLayerNeeded: (temp !== null && temp < 12) || elevation > 1500,
    rainProtectionNeeded: (rainRisk !== null && rainRisk > 25) || (context.weather?.isAlert ?? false),
  };
}

/**
 * 2. Trouve le kit le plus adapté ou génère un kit sur-mesure automatique
 */
export function resolveDeparturePlan(
  context: DepartureHikeContext,
  userKits: CustomKit[],
  userGear: UserEquipmentItem[]
): DeparturePreparationPlan {
  const duration = context.durationHours || Math.max(1, Math.round((context.distanceKm / 3.8) * 10) / 10);
  const consumables = calculateHikeConsumables(context);
  const isBivouac = context.isOvernight && !context.hasRefuges;

  // Évaluation des kits existants
  let bestKit: CustomKit | null = null;
  let bestScore = 0;

  for (const kit of userKits.filter((k) => k.status === 'active')) {
    let score = 50; // base score

    // Matching d'activité / destination
    if (kit.activity.toLowerCase() === (context.difficulty || '').toLowerCase()) score += 15;
    if (kit.for_destination && context.name.toLowerCase().includes(kit.for_destination.toLowerCase())) score += 20;

    // Matching sac de couchage / tente si nuitée
    const hasShelter = kit.items.some((i) => i.category.toLowerCase().includes('couchage') || i.category.toLowerCase().includes('bivouac'));
    if (isBivouac && hasShelter) score += 25;
    if (!context.isOvernight && !hasShelter) score += 15;

    // Matching pluie / météo
    const hasRainGear = kit.items.some((i) => i.item_name.toLowerCase().includes('pluie') || i.item_name.toLowerCase().includes('veste'));
    if (consumables.rainProtectionNeeded && hasRainGear) score += 10;

    if (score > bestScore) {
      bestScore = score;
      bestKit = kit;
    }
  }

  const isAutoGenerated = bestScore < 65 || !bestKit;

  // Création de la liste des items
  const inPackReady: DepartureChecklistItem[] = [];
  const consumablesToPack: DepartureChecklistItem[] = [];
  const securityChecks: DepartureChecklistItem[] = [];
  const missingItems: DepartureChecklistItem[] = [];

  // ── A. Matériel dans le sac ──
  const gearToUse = isAutoGenerated
    ? userGear.filter((g) => g.condition !== 'à_remplacer')
    : (bestKit?.items || []).map((kitItem) => {
        const matching = userGear.find((g) => g.id === kitItem.gear_item_id) ||
                         userGear.find((g) => g.name.toLowerCase() === kitItem.item_name.toLowerCase());
        return matching || {
          id: kitItem.id,
          name: kitItem.item_name,
          category: kitItem.category,
          weight_g: kitItem.weight_g,
          condition: 'bon' as const,
          user_id: '',
        };
      });

  gearToUse.forEach((gear) => {
    const isLent = (gear as UserEquipmentItem).loan_status === 'prêté';
    const needsMaint = (gear as UserEquipmentItem).next_maintenance_date &&
                       new Date((gear as UserEquipmentItem).next_maintenance_date!).getTime() < Date.now();

    if (isLent) {
      securityChecks.push({
        id: `lent-${gear.id}`,
        name: gear.name,
        category: gear.category,
        weightG: gear.weight_g || 0,
        isOwned: true,
        ownedGearId: gear.id,
        isEssential: true,
        status: 'warning',
        warningMessage: `Prêté à ${(gear as UserEquipmentItem).loan_to_name || 'un ami'}`,
        actionHint: 'Récupérer ou remplacer',
      });
    } else {
      inPackReady.push({
        id: gear.id,
        name: gear.name,
        category: gear.category,
        weightG: gear.weight_g || 0,
        isOwned: true,
        ownedGearId: gear.id,
        isEssential: true,
        status: 'ready',
        warningMessage: needsMaint ? 'Entretien préventif recommandé' : undefined,
      });
    }
  });

  // ── B. Consommables ──
  consumablesToPack.push({
    id: 'cons-water',
    name: `Eau potable (${consumables.waterLiters} L)`,
    category: 'Hydratation',
    weightG: Math.round(consumables.waterLiters * 1000),
    isOwned: true,
    isEssential: true,
    status: 'consumable',
    actionHint: consumables.waterReason,
  });

  if (consumables.foodMealsCount > 0) {
    consumablesToPack.push({
      id: 'cons-meals',
      name: `${consumables.foodMealsCount} repas de randonnée`,
      category: 'Alimentation',
      weightG: consumables.foodMealsCount * 180,
      isOwned: true,
      isEssential: true,
      status: 'consumable',
    });
  }

  consumablesToPack.push({
    id: 'cons-snacks',
    name: `${consumables.snacksCount} en-cas énergétiques`,
    category: 'Alimentation',
    weightG: consumables.snacksCount * 45,
    isOwned: true,
    isEssential: true,
    status: 'consumable',
  });

  if (consumables.fuelGrams > 0) {
    consumablesToPack.push({
      id: 'cons-fuel',
      name: `Cartouche de gaz (${consumables.fuelGrams} g)`,
      category: 'Cuisine',
      weightG: consumables.fuelGrams + 100,
      isOwned: true,
      isEssential: false,
      status: 'consumable',
    });
  }

  // ── C. Sécurité & Météo ──
  if (consumables.rainProtectionNeeded) {
    const hasRain = inPackReady.some((i) => i.name.toLowerCase().includes('pluie') || i.name.toLowerCase().includes('veste'));
    if (!hasRain) {
      missingItems.push({
        id: 'req-rain',
        name: 'Veste imperméable / Coupe-vent',
        category: 'Vêtements',
        weightG: 320,
        isOwned: false,
        isEssential: true,
        status: 'missing',
        actionHint: 'Risque de pluie ou vent détecté',
      });
    }
  }

  if (consumables.warmLayerNeeded) {
    const hasWarm = inPackReady.some((i) => i.name.toLowerCase().includes('doudoune') || i.name.toLowerCase().includes('polaire'));
    if (!hasWarm) {
      missingItems.push({
        id: 'req-warm',
        name: 'Couche thermique (Polaire / Doudoune)',
        category: 'Vêtements',
        weightG: 280,
        isOwned: false,
        isEssential: true,
        status: 'missing',
        actionHint: 'Températures fraîches en altitude',
      });
    }
  }

  // Lampe frontale indispensable si > 4h ou nuit
  if (duration >= 4 || context.isOvernight) {
    const hasLamp = inPackReady.some((i) => i.category.toLowerCase().includes('éclairage') || i.name.toLowerCase().includes('frontale'));
    if (!hasLamp) {
      securityChecks.push({
        id: 'sec-lamp',
        name: 'Lampe frontale chargée',
        category: 'Sécurité',
        weightG: 85,
        isOwned: false,
        isEssential: true,
        status: 'warning',
        actionHint: 'Indispensable pour fin de parcours ou nuit',
      });
    }
  }

  // Trousse de premiers secours
  const hasFirstAid = inPackReady.some((i) => i.category.toLowerCase().includes('sécurité') || i.name.toLowerCase().includes('secours') || i.name.toLowerCase().includes('soin'));
  if (!hasFirstAid) {
    securityChecks.push({
      id: 'sec-firstaid',
      name: 'Trousse de secours & couverture de survie',
      category: 'Sécurité',
      weightG: 150,
      isOwned: false,
      isEssential: true,
      status: 'warning',
      actionHint: 'Fond de sac de sécurité obligatoire',
    });
  }

  // Poids total mesuré
  const totalWeight = inPackReady.reduce((s, i) => s + i.weightG, 0) +
                      consumablesToPack.reduce((s, i) => s + i.weightG, 0);

  // Synthèse météo : la mesure telle quelle, ou `null`.
  // L'ancienne version affichait « 15 °C — 20 °C » et
  // « Conditions dégagées » pour une sortie dont personne n avait
  // rien relu. Sans relevé, l'écran doit le dire.
  const temp = context.weather?.tempC ?? null;
  const windKmh = context.weather?.windKmH ?? null;
  const rawPrecip = context.weather?.precipitationProbability ?? null;
  const safeRainPct = rawPrecip === null
    ? null
    : rawPrecip > 1
      ? Math.min(100, Math.round(rawPrecip))
      : Math.min(100, Math.round(rawPrecip * 100));

  const weatherSummary = {
    // La mesure telle quelle. Elle n'est arrondie que pour l'affichage d'un
    // releve : un arrondi au degre pres ne change pas la mesure, un decalage
    // de quelques degres, lui, invente une amplitude qui n'a pas ete relevee.
    tempC: temp === null ? null : Math.round(temp),
    // Aucune amplitude mesuree, donc aucune amplitude affichee. Le champ
    // reste dans le contrat parce qu'un fournisseur quotidien (min/max par
    // journee) le rendra un jour ; le remplir avant serait le deviner.
    tempMinMax: null,
    condition: context.weather?.condition ?? null,
    rainRiskPct: safeRainPct,
    windKmh: windKmh === null ? null : Math.round(windKmh),
    measured: temp !== null,
    advice: temp === null
      ? 'Météo non mesurée pour cette sortie : vérifiez les conditions avant de partir.'
      : consumables.rainProtectionNeeded
      ? 'Prévoyez votre veste imperméable en haut de sac.'
      : consumables.warmLayerNeeded
      ? 'Températures fraîches : couche isolante recommandée.'
      : 'Conditions mesurées favorables pour votre sortie.',
  };

  return {
    hikeContext: context,
    selectedKit: bestKit,
    isAutoGeneratedKit: isAutoGenerated,
    suitabilityScore: Math.min(100, isAutoGenerated ? 88 : bestScore),
    totalPackWeightG: totalWeight,
    consumables,
    checklist: {
      inPackReady,
      consumablesToPack,
      securityChecks,
      missingItems,
    },
    weatherSummary,
  };
}

/**
 * 3. Enregistrement automatique de fin de randonnée pour mettre à jour l'usage du matériel
 */
export async function recordPostHikeGearUsage(gearIds: string[]) {
  if (!gearIds || gearIds.length === 0) return;
  try {
    const supabase = createClient();
    await supabase.rpc('record_hike_gear_usage', { p_gear_ids: gearIds });
  } catch (err) {
    console.warn('[recordPostHikeGearUsage] Error updating gear usage:', err);
  }
}
