import { chromium } from 'playwright-core';
const S = 'http://localhost:4000';
const browser = await chromium.launch();
const errors = [];
const d = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1.5 });
const dp = await d.newPage();
dp.on('pageerror', (e) => errors.push('JS: ' + e.message));
dp.on('response', (r) => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
await dp.goto(`${S}/voyages/y-long-group`, { waitUntil: 'networkidle', timeout: 60000 });
await dp.waitForTimeout(2200);
await dp.screenshot({ path: 'shots/y2-overview-desktop.png' });
await dp.goto(`${S}/voyages/y-long-group/equipage`, { waitUntil: 'networkidle', timeout: 60000 });
await dp.waitForTimeout(1800);
await dp.screenshot({ path: 'shots/y2-equipage-desktop.png' });
const m = await browser.newContext({ viewport: { width: 430, height: 932 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const mp = await m.newPage();
mp.on('pageerror', (e) => errors.push('JS mobile: ' + e.message));
await mp.goto(`${S}/voyages/y-long-group`, { waitUntil: 'networkidle', timeout: 60000 });
await mp.waitForTimeout(2000);
await mp.screenshot({ path: 'shots/y2-overview-mobile.png' });
await mp.goto(`${S}/voyages/y-long-group/budget`, { waitUntil: 'networkidle', timeout: 60000 });
await mp.waitForTimeout(1800);
await mp.screenshot({ path: 'shots/y2-budget-mobile.png' });
console.log('ERREURS:', errors.length ? errors.slice(0, 6) : 'aucune');
await browser.close();
