-- ============================================================
-- Migration: Catalogue 80 produits Le Kit du Voyageur
-- Timestamp: 20260715220000
-- ============================================================

-- ── 1. Étendre shop_products avec les 29 champs du catalogue ──────────────────

ALTER TABLE public.shop_products
  ADD COLUMN IF NOT EXISTS product_id TEXT,
  ADD COLUMN IF NOT EXISTS model TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS category_main TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS category_sub TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS weight_grams INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dimensions TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS materials TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS warranty TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_why TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS advantages_array JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS disadvantages_array JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS alt_premium_id TEXT,
  ADD COLUMN IF NOT EXISTS alt_budget_id TEXT,
  ADD COLUMN IF NOT EXISTS available_europe BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS available_usa BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS score_quality NUMERIC(4,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS score_price NUMERIC(4,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS score_durability NUMERIC(4,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS source_review TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS score_kdv INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS essentiality TEXT DEFAULT 'Recommandé',
  ADD COLUMN IF NOT EXISTS versatility_10 NUMERIC(4,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cabin_compatible BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS repairability_10 NUMERIC(4,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS travel_types_array JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS climates_array JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS justification_ai TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS import_date TIMESTAMPTZ DEFAULT NOW();

-- Unique index sur product_id
CREATE UNIQUE INDEX IF NOT EXISTS idx_shop_products_product_id ON public.shop_products(product_id) WHERE product_id IS NOT NULL;

-- ── 2. Table product_compatibilities ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.product_compatibilities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id_1 TEXT NOT NULL,
  product_id_2 TEXT NOT NULL,
  relation_type TEXT NOT NULL DEFAULT 'compatible_with',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compat_product_1 ON public.product_compatibilities(product_id_1);
CREATE INDEX IF NOT EXISTS idx_compat_product_2 ON public.product_compatibilities(product_id_2);

ALTER TABLE public.product_compatibilities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_compatibilities" ON public.product_compatibilities;
CREATE POLICY "public_read_compatibilities"
  ON public.product_compatibilities FOR SELECT TO public USING (true);

-- ── 3. Table product_alternatives ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.product_alternatives (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  original_product_id TEXT NOT NULL,
  substitute_product_id TEXT NOT NULL,
  priority INTEGER DEFAULT 1,
  reason TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alt_original ON public.product_alternatives(original_product_id);

ALTER TABLE public.product_alternatives ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_alternatives" ON public.product_alternatives;
CREATE POLICY "public_read_alternatives"
  ON public.product_alternatives FOR SELECT TO public USING (true);

-- ── 4. Indexes performance sur shop_products ─────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_shop_products_category_main ON public.shop_products(category_main);
CREATE INDEX IF NOT EXISTS idx_shop_products_score_kdv ON public.shop_products(score_kdv DESC);
CREATE INDEX IF NOT EXISTS idx_shop_products_essentiality ON public.shop_products(essentiality);
CREATE INDEX IF NOT EXISTS idx_shop_products_price_eur ON public.shop_products(price_eur);
CREATE INDEX IF NOT EXISTS idx_shop_products_weight_g ON public.shop_products(weight_g);

-- ── 5. Vider les anciens produits et insérer les 80 produits du catalogue ─────

DELETE FROM public.shop_products WHERE product_id IS NOT NULL OR product_id IS NULL;

-- ── INSERT 80 PRODUITS ────────────────────────────────────────────────────────

INSERT INTO public.shop_products (
  slug, name, brand, model, category, category_main, category_sub,
  weight_g, weight_grams, price_eur, image, image_alt, rating, review_count,
  available, transaction_type, product_id, dimensions, materials, warranty,
  description_why, advantages_array, disadvantages_array,
  alt_premium_id, alt_budget_id, available_europe, available_usa,
  score_quality, score_price, score_durability, source_review,
  score_kdv, essentiality, versatility_10, cabin_compatible,
  repairability_10, travel_types_array, climates_array, justification_ai
) VALUES

-- ── SACS À DOS ────────────────────────────────────────────────────────────────
('osprey-farpoint-40', 'Osprey Farpoint 40', 'Osprey', 'Farpoint 40', 'Sacs à dos', 'Sacs à dos', 'Voyage',
 1420, 1420, 179.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac à dos Osprey Farpoint 40 gris anthracite 40 litres', 4.8, 312,
 true, 'achat', 'P001', '70×35×25 cm', 'Nylon 210D Ripstop', '2 ans constructeur',
 'Le Farpoint 40 est la référence absolue pour le voyage longue durée. Son système de portage suspendu et son accès frontal en font le compagnon idéal pour 3 semaines à 6 mois de voyage.',
 '["Accès frontal pratique","Système de portage suspendu","Compartiment laptop","Compatible cabine selon compagnies"]'::jsonb,
 '["Pas de cadre interne rigide","Ventilation dorsale limitée"]'::jsonb,
 'P003', 'P002', true, true,
 9.0, 8.5, 8.5, 'OutdoorGearLab 2025',
 88, 'Indispensable', 9.5, true,
 7.0, '["Backpacking","Tour du monde","Avion","Trek"]'::jsonb, '["Tempéré","Tropical","Montagne"]'::jsonb,
 'Meilleur rapport polyvalence/poids de sa catégorie. Recommandé pour 80% des voyageurs.'),

('deuter-speed-lite-20', 'Deuter Speed Lite 20', 'Deuter', 'Speed Lite 20', 'Sacs à dos', 'Sacs à dos', 'Randonnée légère',
 690, 690, 89.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac à dos Deuter Speed Lite 20 rouge 20 litres ultraléger', 4.3, 187,
 true, 'achat', 'P002', '50×28×18 cm', 'Nylon 210D', '3 ans constructeur',
 'Le Speed Lite 20 est le choix idéal pour les randonnées à la journée et les sorties légères. Léger et compact, il ne sacrifie pas le confort.',
 '["Très léger","Compact","Bon rapport qualité/prix","Dos ventilé"]'::jsonb,
 '["Volume limité","Pas de ceinture lombaire rembourrée"]'::jsonb,
 'P001', NULL, true, true,
 8.0, 9.0, 8.0, 'Randonner Malin 2025',
 72, 'Recommandé', 7.0, true,
 8.0, '["Randonnée","Trek","Weekend"]'::jsonb, '["Tempéré","Montagne"]'::jsonb,
 'Excellent choix budget pour les randonnées courtes. Idéal comme sac de jour.'),

('gregory-baltoro-65', 'Gregory Baltoro 65', 'Gregory', 'Baltoro 65', 'Sacs à dos', 'Sacs à dos', 'Trekking',
 2100, 2100, 289.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac à dos Gregory Baltoro 65 litres bleu pour trekking', 4.7, 234,
 true, 'achat', 'P003', '80×38×30 cm', 'Nylon 420D HD', '2 ans constructeur',
 'Le Baltoro 65 est le sac de trekking multi-jours par excellence. Son système de suspension Response A3 s''adapte à votre morphologie pour un confort optimal sur les longues distances.',
 '["Suspension adaptative","Très confortable","Nombreux rangements","Accès latéral"]'::jsonb,
 '["Lourd","Prix élevé","Encombrant en avion"]'::jsonb,
 NULL, 'P001', true, true,
 9.5, 7.0, 9.0, 'Backpacker Magazine 2025',
 82, 'Recommandé', 6.5, false,
 7.5, '["Trek","Camping","Expédition"]'::jsonb, '["Montagne","Tempéré","Arctique"]'::jsonb,
 'Référence pour les treks de plusieurs semaines avec portage lourd.'),

-- ── TENTES ────────────────────────────────────────────────────────────────────
('msr-hubba-hubba-nx', 'MSR Hubba Hubba NX 2P', 'MSR', 'Hubba Hubba NX', 'Tentes', 'Tentes', '3 saisons',
 1720, 1720, 549.00, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80', 'Tente MSR Hubba Hubba NX 2 places orange montée en montagne', 4.9, 198,
 true, 'achat', 'P004', '213×127×97 cm', 'Nylon 20D Ripstop', '2 ans constructeur',
 'La Hubba Hubba NX est la tente 2 places de référence pour le trekking léger. Son architecture autoportante et ses 1720g en font le choix des randonneurs exigeants.',
 '["Autoportante","Très légère","Double paroi","Bonne ventilation"]'::jsonb,
 '["Prix élevé","Montage complexe par vent fort"]'::jsonb,
 'P006', 'P005', true, true,
 9.5, 7.0, 9.0, 'OutdoorGearLab 2025',
 91, 'Indispensable', 8.5, false,
 8.0, '["Trek","Camping","Backpacking","Expédition"]'::jsonb, '["Montagne","Tempéré","Arctique"]'::jsonb,
 'Meilleure tente 2P légère du marché. Investissement durable sur 8-10 ans.'),

('big-agnes-copper-spur', 'Big Agnes Copper Spur HV UL2', 'Big Agnes', 'Copper Spur HV UL2', 'Tentes', 'Tentes', 'Ultralight',
 1020, 1020, 649.00, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80', 'Tente Big Agnes Copper Spur HV UL2 orange ultraléger', 4.8, 156,
 true, 'achat', 'P005', '213×127×100 cm', 'Nylon 15D Ripstop', '2 ans constructeur',
 'La Copper Spur HV UL2 est la référence ultralight pour les randonneurs qui ne veulent pas sacrifier l''espace. Moins d''1 kg pour 2 personnes, c''est exceptionnel.',
 '["Ultra légère","Espace intérieur généreux","Double paroi","Haute résistance"]'::jsonb,
 '["Prix très élevé","Tissu délicat","Moins robuste que MSR"]'::jsonb,
 NULL, 'P004', true, true,
 9.0, 6.0, 8.0, 'Ultralight Outdoor Gear 2025',
 85, 'Recommandé', 7.5, false,
 6.0, '["Trek","Backpacking","Expédition ultralight"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Pour les ultralight addicts. Fragile mais incomparable en légèreté.'),

('nemo-hornet-elite', 'NEMO Hornet Elite OSMO 2P', 'NEMO', 'Hornet Elite OSMO', 'Tentes', 'Tentes', 'Ultralight',
 790, 790, 699.00, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80', 'Tente NEMO Hornet Elite OSMO 2 places verte ultraléger', 4.7, 89,
 true, 'achat', 'P006', '208×122×96 cm', 'OSMO Nylon 10D', '2 ans constructeur',
 'La Hornet Elite OSMO repousse les limites de la légèreté avec son tissu OSMO révolutionnaire. 790g pour une tente 2 places complète, c''est le summum de la technologie.',
 '["La plus légère de sa catégorie","Tissu OSMO haute performance","Bonne résistance à la pluie"]'::jsonb,
 '["Prix premium","Tissu très délicat","Espace limité"]'::jsonb,
 NULL, 'P005', true, true,
 9.0, 5.5, 7.5, 'Backpacker Magazine 2025',
 80, 'Confort', 7.0, false,
 5.0, '["Trek ultralight","Expédition"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Pour les puristes du poids. Nécessite soin et expérience.'),

-- ── COUCHAGE ──────────────────────────────────────────────────────────────────
('sea-to-summit-spark-sp1', 'Sea to Summit Spark SP1', 'Sea to Summit', 'Spark SP1', 'Couchage', 'Couchage', 'Sacs de couchage',
 490, 490, 299.00, 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=600&q=80', 'Sac de couchage Sea to Summit Spark SP1 ultra léger bleu compact', 4.7, 156,
 true, 'achat', 'P007', '30×15 cm (compressé)', 'Duvet 850+ cuin', '2 ans constructeur',
 'Le Spark SP1 est le sac de couchage ultraléger de référence pour les températures estivales. Son duvet 850+ cuin offre un rapport chaleur/poids exceptionnel.',
 '["Très léger","Duvet haute qualité","Compressible","Confort +5°C"]'::jsonb,
 '["Prix élevé","Pas adapté au froid","Délicat à l''humidité"]'::jsonb,
 'P009', 'P008', true, true,
 9.0, 7.0, 8.0, 'OutdoorGearLab 2025',
 85, 'Recommandé', 8.0, true,
 7.0, '["Trek","Backpacking","Tour du monde"]'::jsonb, '["Tempéré","Tropical"]'::jsonb,
 'Référence légèreté pour les voyages en été. Investissement qui dure 10+ ans.'),

('western-mountaineering-ultralite', 'Western Mountaineering UltraLite', 'Western Mountaineering', 'UltraLite', 'Couchage', 'Couchage', 'Sacs de couchage',
 567, 567, 499.00, 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=600&q=80', 'Sac de couchage Western Mountaineering UltraLite duvet premium', 4.9, 78,
 true, 'achat', 'P008', '28×14 cm (compressé)', 'Duvet 850 cuin goose down', '2 ans constructeur',
 'Le UltraLite de Western Mountaineering est le sac de couchage premium par excellence. Fabriqué artisanalement aux USA, il représente le summum de la qualité.',
 '["Qualité artisanale","Duvet exceptionnel","Durabilité 15+ ans","Confort 0°C"]'::jsonb,
 '["Prix très élevé","Disponibilité limitée","Livraison longue"]'::jsonb,
 NULL, 'P007', true, true,
 10.0, 5.0, 10.0, 'Ultralight Outdoor Gear 2025',
 88, 'Recommandé', 7.5, true,
 9.0, '["Trek","Expédition","Camping"]'::jsonb, '["Montagne","Tempéré","Arctique"]'::jsonb,
 'Le meilleur sac de couchage léger du marché. Achat pour la vie.'),

('nemo-tensor-insulated', 'NEMO Tensor Insulated', 'NEMO', 'Tensor Insulated', 'Couchage', 'Couchage', 'Matelas',
 510, 510, 189.00, 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=600&q=80', 'Matelas gonflable NEMO Tensor Insulated orange déplié camping', 4.8, 201,
 true, 'achat', 'P009', '183×51×8 cm (gonflé)', 'Nylon 30D Ripstop', '2 ans constructeur',
 'Le Tensor Insulated est le matelas gonflable de référence pour les 3 saisons. Son isolation thermique et son confort en font le choix des randonneurs exigeants.',
 '["Excellent confort","Bonne isolation R-value 3.5","Léger","Silencieux"]'::jsonb,
 '["Prix élevé","Gonflage à la bouche fatigant","Délicat aux pierres"]'::jsonb,
 'P010', NULL, true, true,
 9.0, 7.5, 8.0, 'OutdoorGearLab 2025',
 87, 'Indispensable', 8.5, true,
 6.0, '["Trek","Camping","Backpacking"]'::jsonb, '["Montagne","Tempéré","Arctique"]'::jsonb,
 'Meilleur matelas gonflable léger du marché. Indispensable pour dormir confortablement.'),

('therm-a-rest-neoair-xlite', 'Therm-a-Rest NeoAir XLite NXT', 'Therm-a-Rest', 'NeoAir XLite NXT', 'Couchage', 'Couchage', 'Matelas',
 354, 354, 219.00, 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=600&q=80', 'Matelas gonflable Therm-a-Rest NeoAir XLite NXT argent ultraléger', 4.7, 289,
 true, 'achat', 'P010', '183×51×6 cm (gonflé)', 'Nylon 30D', '2 ans constructeur',
 'Le NeoAir XLite NXT est le matelas ultraléger de référence. Son R-value de 4.2 et ses 354g en font le choix des randonneurs qui ne veulent pas sacrifier l''isolation.',
 '["Ultra léger","R-value 4.2 excellent","Compact","Technologie ThermaCapture"]'::jsonb,
 '["Bruyant","Prix élevé","Gonflage à la bouche"]'::jsonb,
 NULL, 'P009', true, true,
 9.0, 7.0, 8.5, 'Backpacker Magazine 2025',
 89, 'Recommandé', 8.0, true,
 6.5, '["Trek","Backpacking","Expédition"]'::jsonb, '["Montagne","Tempéré","Arctique"]'::jsonb,
 'Référence ultralight pour l''isolation. Idéal 3 saisons et hiver léger.'),

-- ── ÉCLAIRAGE ─────────────────────────────────────────────────────────────────
('petzl-actik-core', 'Petzl Actik Core', 'Petzl', 'Actik Core', 'Éclairage', 'Éclairage', 'Frontales',
 85, 85, 49.00, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', 'Lampe frontale Petzl Actik Core rouge 450 lumens rechargeable', 4.6, 423,
 true, 'achat', 'P011', '7×4×3 cm', 'ABS, polycarbonate', '3 ans constructeur',
 'La Actik Core est la frontale rechargeable de référence pour la randonnée. Ses 450 lumens et sa batterie rechargeable en font un choix polyvalent et économique.',
 '["Rechargeable USB","450 lumens","Légère","Mode rouge"]'::jsonb,
 '["Batterie non remplaçable en urgence","Faisceau large uniquement"]'::jsonb,
 'P013', 'P012', true, true,
 8.5, 9.0, 8.0, 'Randonner Malin 2025',
 84, 'Indispensable', 9.0, true,
 8.5, '["Trek","Camping","Backpacking","Tour du monde"]'::jsonb, '["Tous"]'::jsonb,
 'Meilleur rapport qualité/prix en frontale rechargeable. Indispensable dans tout kit.'),

('black-diamond-spot-400', 'Black Diamond Spot 400', 'Black Diamond', 'Spot 400', 'Éclairage', 'Éclairage', 'Frontales',
 91, 91, 39.00, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', 'Lampe frontale Black Diamond Spot 400 lumens noire imperméable', 4.5, 287,
 true, 'achat', 'P012', '7×4×3 cm', 'ABS', '3 ans constructeur',
 'La Spot 400 est la frontale polyvalente de Black Diamond. Ses 400 lumens et son étanchéité IPX8 en font un choix fiable pour toutes les conditions.',
 '["IPX8 étanche","400 lumens","Piles AAA standard","Robuste"]'::jsonb,
 '["Piles non rechargeables","Moins lumineux que Petzl"]'::jsonb,
 'P011', NULL, true, true,
 8.0, 9.5, 8.5, 'OutdoorGearLab 2025',
 79, 'Recommandé', 8.5, true,
 9.0, '["Trek","Camping","Backpacking"]'::jsonb, '["Tous"]'::jsonb,
 'Excellent choix pour les voyages longs où les piles AAA sont accessibles partout.'),

('petzl-nao-rl', 'Petzl NAO RL', 'Petzl', 'NAO RL', 'Éclairage', 'Éclairage', 'Frontales premium',
 175, 175, 149.00, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', 'Lampe frontale Petzl NAO RL 1500 lumens rechargeable premium', 4.8, 134,
 true, 'achat', 'P013', '8×5×4 cm', 'ABS, polycarbonate', '3 ans constructeur',
 'La NAO RL est la frontale premium de Petzl avec 1500 lumens et recharge rapide. Son éclairage réactif adapte automatiquement l''intensité à l''environnement.',
 '["1500 lumens","Éclairage réactif","Recharge rapide","Bluetooth"]'::jsonb,
 '["Prix élevé","Lourde","Complexe à paramétrer"]'::jsonb,
 NULL, 'P011', true, true,
 9.5, 6.5, 8.5, 'Petzl Official 2025',
 78, 'Confort', 7.5, true,
 8.0, '["Alpinisme","Spéléologie","Trail running"]'::jsonb, '["Montagne","Nuit"]'::jsonb,
 'Pour les activités nocturnes intensives. Surdimensionné pour le voyage classique.'),

-- ── EAU ───────────────────────────────────────────────────────────────────────
('katadyn-befree-1l', 'Katadyn BeFree 1L', 'Katadyn', 'BeFree 1L', 'Eau', 'Eau', 'Filtration',
 56, 56, 44.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Filtre à eau Katadyn BeFree 1 litre bleu transparent randonnée', 4.7, 334,
 true, 'achat', 'P014', '25×8 cm', 'Fibre creuse 0.1 micron', '2 ans constructeur',
 'Le BeFree est le filtre à eau le plus pratique du marché. Son intégration dans une gourde souple permet de boire directement depuis n''importe quelle source.',
 '["Très léger","Boire directement","Débit rapide","Facile à nettoyer"]'::jsonb,
 '["Ne filtre pas les virus","Gourde souple fragile"]'::jsonb,
 'P016', NULL, true, true,
 8.5, 9.0, 7.5, 'OutdoorGearLab 2025',
 88, 'Indispensable', 9.5, true,
 7.0, '["Trek","Backpacking","Tour du monde"]'::jsonb, '["Montagne","Tempéré","Tropical"]'::jsonb,
 'Indispensable pour tout trek en zone sauvage. Léger et efficace.'),

('sawyer-squeeze', 'Sawyer Squeeze', 'Sawyer', 'Squeeze', 'Eau', 'Eau', 'Filtration',
 85, 85, 35.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Filtre à eau Sawyer Squeeze bleu avec pochette souple', 4.6, 445,
 true, 'achat', 'P015', '15×5 cm', 'Fibre creuse 0.1 micron', '2 ans constructeur',
 'Le Sawyer Squeeze est le filtre à eau le plus populaire chez les randonneurs. Son rapport qualité/prix imbattable et sa légèreté en font un incontournable.',
 '["Très léger","Prix abordable","Lavable","Longue durée de vie"]'::jsonb,
 '["Débit plus lent que BeFree","Pochette souple fragile"]'::jsonb,
 'P014', NULL, true, true,
 8.0, 9.5, 8.0, 'Backpacker Magazine 2025',
 85, 'Indispensable', 9.0, true,
 8.0, '["Trek","Backpacking","Camping"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Meilleur rapport qualité/prix en filtration. Référence mondiale des randonneurs.'),

('msr-guardian-purifier', 'MSR Guardian Purifier', 'MSR', 'Guardian Purifier', 'Eau', 'Eau', 'Purification',
 490, 490, 349.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Purificateur d eau MSR Guardian pompe manuelle gris argent', 4.9, 112,
 true, 'achat', 'P016', '20×8 cm', 'Fibre creuse 0.02 micron', '2 ans constructeur',
 'Le Guardian est le purificateur d''eau le plus complet du marché. Il élimine bactéries, protozoaires ET virus, ce qui en fait le choix pour les zones à risque élevé.',
 '["Élimine virus","Débit rapide","Auto-nettoyant","Militaire grade"]'::jsonb,
 '["Lourd","Prix très élevé","Encombrant"]'::jsonb,
 NULL, 'P014', true, true,
 10.0, 5.0, 10.0, 'MSR Official 2025',
 82, 'Recommandé', 7.0, false,
 9.0, '["Expédition","Trek zones tropicales","Voyage humanitaire"]'::jsonb, '["Tropical","Désert","Tous"]'::jsonb,
 'Pour les zones à risque viral élevé. Overkill pour l''Europe mais indispensable en Asie/Afrique.'),

-- ── NAVIGATION ────────────────────────────────────────────────────────────────
('garmin-inreach-mini-2', 'Garmin inReach Mini 2', 'Garmin', 'inReach Mini 2', 'Navigation', 'Navigation', 'Communicateurs satellite',
 100, 100, 349.00, 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80', 'Communicateur satellite Garmin inReach Mini 2 orange avec antenne', 4.9, 178,
 true, 'achat', 'P017', '10×5×2.5 cm', 'Polycarbonate renforcé', '1 an constructeur',
 'Le inReach Mini 2 est le communicateur satellite le plus compact du marché. En cas d''urgence en zone sans réseau, il peut sauver des vies. Abonnement mensuel requis.',
 '["Léger et compact","SOS mondial","Messagerie satellite","Tracking GPS"]'::jsonb,
 '["Abonnement mensuel obligatoire","Prix élevé","Pas de cartographie"]'::jsonb,
 'P019', NULL, true, true,
 9.5, 6.5, 9.0, 'OutdoorGearLab 2025',
 87, 'Recommandé', 8.5, true,
 7.0, '["Expédition","Trek isolé","Tour du monde"]'::jsonb, '["Tous"]'::jsonb,
 'Indispensable pour les zones isolées. L''assurance vie du randonneur solo.'),

('garmin-gpsmap-67', 'Garmin GPSMAP 67', 'Garmin', 'GPSMAP 67', 'Navigation', 'Navigation', 'GPS',
 218, 218, 399.00, 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80', 'GPS Garmin GPSMAP 67 jaune avec écran couleur et antenne', 4.7, 145,
 true, 'achat', 'P018', '16×6×3 cm', 'Polycarbonate', '1 an constructeur',
 'Le GPSMAP 67 est le GPS de randonnée le plus complet de Garmin. Son écran couleur, sa batterie longue durée et ses cartes topographiques en font la référence.',
 '["Cartes topo incluses","Batterie 36h","Multi-GNSS","Robuste IPX7"]'::jsonb,
 '["Lourd","Prix élevé","Interface vieillissante"]'::jsonb,
 NULL, 'P017', true, true,
 9.0, 6.0, 9.0, 'Garmin Official 2025',
 80, 'Recommandé', 7.0, false,
 8.0, '["Trek","Expédition","Randonnée"]'::jsonb, '["Montagne","Désert","Arctique"]'::jsonb,
 'Pour les treks techniques nécessitant une navigation précise sans smartphone.'),

('suunto-9-peak-pro', 'Suunto 9 Peak Pro', 'Suunto', '9 Peak Pro', 'Navigation', 'Navigation', 'Montres GPS',
 75, 75, 699.00, 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80', 'Montre GPS Suunto 9 Peak Pro noire avec bracelet silicone', 4.8, 203,
 true, 'achat', 'P019', '43mm diamètre', 'Titane, verre saphir', '2 ans constructeur',
 'La Suunto 9 Peak Pro est la montre GPS premium pour les aventuriers. Son boîtier en titane, son verre saphir et sa batterie de 170h en font une montre pour la vie.',
 '["Batterie 170h","Boîtier titane","Verre saphir","Navigation précise"]'::jsonb,
 '["Prix très élevé","Interface complexe","Pas de paiement NFC"]'::jsonb,
 NULL, 'P017', true, true,
 9.5, 5.0, 10.0, 'DC Rainmaker 2025',
 83, 'Confort', 8.0, true,
 9.0, '["Trail running","Trek","Triathlon","Tour du monde"]'::jsonb, '["Tous"]'::jsonb,
 'Pour les sportifs qui veulent une montre GPS premium durable. Luxe justifié.'),

-- ── VÊTEMENTS ─────────────────────────────────────────────────────────────────
('arc-teryx-beta-ar', 'Arc''teryx Beta AR', 'Arc''teryx', 'Beta AR', 'Vêtements', 'Vêtements', 'Vestes imperméables',
 485, 485, 699.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Veste de randonnée Arc teryx Beta AR rouge imperméable Gore-Tex', 4.9, 89,
 true, 'achat', 'P020', 'S-XXL', 'Gore-Tex Pro 3L', '2 ans constructeur',
 'La Beta AR est la veste imperméable de référence pour les conditions extrêmes. Son Gore-Tex Pro 3 couches offre une imperméabilité et une respirabilité incomparables.',
 '["Gore-Tex Pro 3L","Très respirante","Coupe technique","Durable 10+ ans"]'::jsonb,
 '["Prix très élevé","Entretien spécifique","Pas de doublure"]'::jsonb,
 NULL, 'P021', true, true,
 10.0, 5.0, 10.0, 'OutdoorGearLab 2025',
 88, 'Recommandé', 8.0, true,
 9.0, '["Trek","Alpinisme","Expédition"]'::jsonb, '["Montagne","Arctique","Tempéré pluvieux"]'::jsonb,
 'La meilleure veste imperméable du marché. Investissement pour 10-15 ans.'),

('patagonia-torrentshell-3l', 'Patagonia Torrentshell 3L', 'Patagonia', 'Torrentshell 3L', 'Vêtements', 'Vêtements', 'Vestes imperméables',
 340, 340, 229.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Veste imperméable Patagonia Torrentshell 3L bleue légère', 4.6, 312,
 true, 'achat', 'P021', 'XS-XXL', 'H2No Performance Standard 3L', '2 ans constructeur',
 'La Torrentshell 3L est la veste imperméable polyvalente de Patagonia. Son rapport qualité/prix et son engagement environnemental en font un choix éthique et performant.',
 '["Bon rapport Q/P","Matériaux recyclés","Légère","Polyvalente"]'::jsonb,
 '["Moins respirante qu''Arc''teryx","Coutures non entièrement soudées"]'::jsonb,
 'P020', NULL, true, true,
 8.5, 8.5, 8.0, 'Patagonia Official 2025',
 82, 'Recommandé', 8.5, true,
 8.0, '["Trek","Randonnée","Voyage urbain","Backpacking"]'::jsonb, '["Tempéré","Montagne"]'::jsonb,
 'Excellent choix éco-responsable. Parfait pour 90% des voyageurs.'),

('icebreaker-merino-200', 'Icebreaker Merino 200 Oasis', 'Icebreaker', 'Merino 200 Oasis', 'Vêtements', 'Vêtements', 'Sous-vêtements thermiques',
 155, 155, 89.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'T-shirt thermique Icebreaker Merino 200 Oasis bleu marine laine mérinos', 4.7, 445,
 true, 'achat', 'P022', 'XS-XXL', 'Laine mérinos 200g/m²', '2 ans constructeur',
 'Le Merino 200 Oasis est le sous-vêtement thermique de référence. La laine mérinos régule la température, absorbe l''humidité et ne retient pas les odeurs.',
 '["Anti-odeur naturel","Régulation thermique","Confortable","Lavable machine"]'::jsonb,
 '["Prix élevé","Séchage lent","Délicat au lavage"]'::jsonb,
 NULL, 'P023', true, true,
 9.0, 7.5, 8.0, 'OutdoorGearLab 2025',
 86, 'Indispensable', 9.5, true,
 7.0, '["Trek","Tour du monde","Backpacking","Business"]'::jsonb, '["Tous"]'::jsonb,
 'Indispensable pour voyager avec peu de vêtements. La laine mérinos change la vie.'),

('smartwool-phd-merino', 'Smartwool PhD Merino 150', 'Smartwool', 'PhD Merino 150', 'Vêtements', 'Vêtements', 'Sous-vêtements thermiques',
 130, 130, 75.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'T-shirt Smartwool PhD Merino 150 gris léger laine mérinos', 4.6, 267,
 true, 'achat', 'P023', 'XS-XXL', 'Laine mérinos 150g/m²', '2 ans constructeur',
 'Le PhD Merino 150 est le t-shirt mérinos léger idéal pour les voyages en climat chaud. Plus léger que le 200, il convient parfaitement aux destinations tropicales.',
 '["Très léger","Anti-odeur","Séchage rapide","Polyvalent"]'::jsonb,
 '["Moins chaud que 200","Prix élevé"]'::jsonb,
 'P022', NULL, true, true,
 8.5, 8.0, 7.5, 'Smartwool Official 2025',
 82, 'Recommandé', 9.0, true,
 7.0, '["Tour du monde","Backpacking","Voyage tropical"]'::jsonb, '["Tropical","Tempéré"]'::jsonb,
 'Parfait pour les voyages en zone chaude. Légèreté et anti-odeur.'),

-- ── CHAUSSURES ────────────────────────────────────────────────────────────────
('salomon-x-ultra-4', 'Salomon X Ultra 4 GTX', 'Salomon', 'X Ultra 4 GTX', 'Chaussures', 'Chaussures', 'Chaussures de randonnée',
 680, 680, 159.00, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', 'Chaussures de randonnée Salomon X Ultra 4 GTX grises imperméables', 4.7, 567,
 true, 'achat', 'P024', '36-48', 'Gore-Tex, Contagrip', '2 ans constructeur',
 'Les X Ultra 4 GTX sont les chaussures de randonnée polyvalentes de référence. Leur semelle Contagrip et leur membrane Gore-Tex en font un choix fiable pour tous les terrains.',
 '["Gore-Tex imperméable","Semelle Contagrip","Légères","Polyvalentes"]'::jsonb,
 '["Pas idéales pour portage lourd","Tige basse"]'::jsonb,
 'P026', 'P025', true, true,
 9.0, 8.5, 8.5, 'OutdoorGearLab 2025',
 88, 'Indispensable', 9.0, false,
 8.0, '["Trek","Randonnée","Backpacking"]'::jsonb, '["Montagne","Tempéré","Pluvieux"]'::jsonb,
 'Référence chaussures de randonnée légères. Excellent choix pour 80% des treks.'),

('hoka-speedgoat-5', 'Hoka Speedgoat 5', 'Hoka', 'Speedgoat 5', 'Chaussures', 'Chaussures', 'Trail running',
 298, 298, 149.00, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', 'Chaussures trail running Hoka Speedgoat 5 orange avec semelle épaisse', 4.8, 389,
 true, 'achat', 'P025', '36-48', 'Mesh, Vibram Megagrip', '1 an constructeur',
 'Les Speedgoat 5 sont les chaussures de trail running les plus populaires. Leur amorti maximaliste et leur grip Vibram en font un choix excellent pour les longues distances.',
 '["Amorti maximaliste","Grip Vibram excellent","Légères","Confortables"]'::jsonb,
 '["Pas imperméables","Durée de vie limitée","Pas pour portage lourd"]'::jsonb,
 'P024', NULL, true, true,
 9.0, 8.0, 7.0, 'iRunFar 2025',
 80, 'Recommandé', 8.5, false,
 6.0, '["Trail running","Trek léger","Randonnée"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Pour les randonneurs qui veulent légèreté et amorti. Pas pour terrain humide.'),

('la-sportiva-trango-tech', 'La Sportiva Trango Tech GTX', 'La Sportiva', 'Trango Tech GTX', 'Chaussures', 'Chaussures', 'Chaussures alpinisme',
 780, 780, 299.00, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', 'Chaussures alpinisme La Sportiva Trango Tech GTX noires rigides', 4.8, 134,
 true, 'achat', 'P026', '36-47', 'Gore-Tex, Vibram', '2 ans constructeur',
 'Les Trango Tech GTX sont les chaussures d''alpinisme légères de référence. Leur rigidité partielle et leur compatibilité crampon en font le choix des alpinistes modernes.',
 '["Compatible crampon","Gore-Tex","Rigidité partielle","Légères pour alpinisme"]'::jsonb,
 '["Prix élevé","Pas pour randonnée classique","Pointure serrée"]'::jsonb,
 NULL, 'P024', true, true,
 9.5, 6.5, 9.0, 'Alpinist Magazine 2025',
 82, 'Recommandé', 6.0, false,
 8.0, '["Alpinisme","Expédition","Trek technique"]'::jsonb, '["Montagne","Arctique","Glacier"]'::jsonb,
 'Pour les alpinistes et randonneurs en terrain technique. Surdimensionné pour le trek classique.'),

-- ── CUISINE ───────────────────────────────────────────────────────────────────
('msr-windburner-personal', 'MSR WindBurner Personal', 'MSR', 'WindBurner Personal', 'Cuisine', 'Cuisine', 'Réchauds',
 392, 392, 119.00, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', 'Réchaud MSR WindBurner Personal avec casserole intégrée gris', 4.8, 234,
 true, 'achat', 'P027', '11×11×14 cm (rangé)', 'Acier inox, aluminium', '2 ans constructeur',
 'Le WindBurner Personal est le système de cuisson tout-en-un le plus efficace du marché. Son brûleur intégré résiste au vent et son efficacité thermique réduit la consommation de gaz.',
 '["Résistant au vent","Système intégré","Efficace","Compact"]'::jsonb,
 '["Pas compatible autres casseroles","Prix élevé","Cartouche propriétaire"]'::jsonb,
 'P029', 'P028', true, true,
 9.0, 7.5, 9.0, 'OutdoorGearLab 2025',
 87, 'Indispensable', 8.5, true,
 8.0, '["Trek","Backpacking","Camping","Expédition"]'::jsonb, '["Montagne","Arctique","Tempéré"]'::jsonb,
 'Meilleur système de cuisson pour le trek. Indispensable pour les sorties autonomes.'),

('jetboil-flash', 'Jetboil Flash', 'Jetboil', 'Flash', 'Cuisine', 'Cuisine', 'Réchauds',
 371, 371, 99.00, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', 'Réchaud Jetboil Flash orange avec tasse intégrée système rapide', 4.7, 345,
 true, 'achat', 'P028', '10×10×15 cm (rangé)', 'Aluminium anodisé', '2 ans constructeur',
 'Le Jetboil Flash est le réchaud le plus rapide du marché. Il fait bouillir 500ml en 100 secondes, ce qui en fait le choix des randonneurs pressés.',
 '["Très rapide","Indicateur de chaleur","Compact","Populaire"]'::jsonb,
 '["Moins résistant au vent que WindBurner","Cartouche propriétaire"]'::jsonb,
 'P027', NULL, true, true,
 8.5, 8.5, 8.0, 'Backpacker Magazine 2025',
 83, 'Recommandé', 8.0, true,
 7.5, '["Trek","Backpacking","Camping"]'::jsonb, '["Tempéré","Montagne"]'::jsonb,
 'Excellent choix pour la rapidité. Moins efficace par vent fort.'),

('snow-peak-titanium-spork', 'Snow Peak Titanium Spork', 'Snow Peak', 'Titanium Spork', 'Cuisine', 'Cuisine', 'Couverts',
 27, 27, 19.00, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', 'Cuillère fourchette Snow Peak en titane ultraléger argenté', 4.8, 678,
 true, 'achat', 'P029', '17×4 cm', 'Titane grade 2', '2 ans constructeur',
 'Le Titanium Spork est l''ustensile de cuisine ultraléger de référence. 27g en titane, indestructible et polyvalent, c''est l''accessoire indispensable de tout kit léger.',
 '["Ultra léger","Indestructible","Polyvalent","Compact"]'::jsonb,
 '["Prix élevé pour un couvert","Pas de couteau"]'::jsonb,
 NULL, NULL, true, true,
 9.0, 8.0, 10.0, 'Ultralight Outdoor Gear 2025',
 82, 'Recommandé', 10.0, true,
 10.0, '["Tous"]'::jsonb, '["Tous"]'::jsonb,
 'Achat pour la vie. Le couvert ultraléger indispensable.'),

-- ── SÉCURITÉ ──────────────────────────────────────────────────────────────────
('adventure-medical-kits-ultralight', 'Adventure Medical Kits Ultralight', 'Adventure Medical', 'Ultralight 3.0', 'Sécurité', 'Sécurité', 'Trousses de secours',
 142, 142, 39.00, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', 'Trousse de premiers secours Adventure Medical Kits Ultralight rouge compacte', 4.7, 234,
 true, 'achat', 'P030', '15×10×5 cm', 'Nylon 210D', '2 ans constructeur',
 'La trousse Ultralight 3.0 est la référence pour les randonneurs. Légère et complète, elle contient tout le nécessaire pour les urgences courantes en montagne.',
 '["Légère","Complète","Organisée","Guide inclus"]'::jsonb,
 '["Pas de médicaments","Contenu limité pour expéditions"]'::jsonb,
 'P032', NULL, true, true,
 8.5, 9.0, 8.0, 'OutdoorGearLab 2025',
 85, 'Indispensable', 9.5, true,
 8.0, '["Trek","Backpacking","Tour du monde","Camping"]'::jsonb, '["Tous"]'::jsonb,
 'Indispensable dans tout kit. La sécurité ne se négocie pas.'),

('lifesystems-explorer-first-aid', 'Lifesystems Explorer First Aid', 'Lifesystems', 'Explorer First Aid', 'Sécurité', 'Sécurité', 'Trousses de secours',
 198, 198, 29.00, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', 'Trousse de secours Lifesystems Explorer First Aid verte complète', 4.5, 156,
 true, 'achat', 'P031', '18×12×6 cm', 'Nylon', '2 ans constructeur',
 'La Explorer First Aid est la trousse de secours complète de Lifesystems. Plus lourde que l''Ultralight mais plus complète, elle convient aux groupes et aux expéditions.',
 '["Très complète","Prix abordable","Bonne organisation","Groupe 4 personnes"]'::jsonb,
 '["Plus lourde","Moins compacte"]'::jsonb,
 'P030', NULL, true, true,
 8.0, 9.5, 8.0, 'Lifesystems Official 2025',
 78, 'Recommandé', 8.5, true,
 8.0, '["Trek groupe","Camping famille","Expédition"]'::jsonb, '["Tous"]'::jsonb,
 'Meilleur choix pour les groupes. Rapport qualité/prix excellent.'),

('petzl-grigri-plus', 'Petzl Grigri+', 'Petzl', 'Grigri+', 'Sécurité', 'Sécurité', 'Équipement escalade',
 175, 175, 89.00, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', 'Assureur Petzl Grigri Plus noir avec poignée anti-panique', 4.9, 345,
 true, 'achat', 'P032', '12×8×4 cm', 'Aluminium', '3 ans constructeur',
 'Le Grigri+ est l''assureur de référence pour l''escalade. Son système anti-panique et son blocage assisté en font le choix le plus sûr pour l''escalade sportive.',
 '["Blocage assisté","Anti-panique","Robuste","Standard industrie"]'::jsonb,
 '["Lourd pour alpinisme","Prix élevé","Apprentissage nécessaire"]'::jsonb,
 NULL, NULL, true, true,
 10.0, 7.5, 10.0, 'Petzl Official 2025',
 80, 'Recommandé', 5.0, false,
 9.5, '["Escalade","Via ferrata","Alpinisme"]'::jsonb, '["Montagne","Falaise"]'::jsonb,
 'Indispensable pour l''escalade. Inutile pour le trek classique.'),

-- ── ÉLECTRONIQUE ──────────────────────────────────────────────────────────────
('anker-powercore-26800', 'Anker PowerCore 26800', 'Anker', 'PowerCore 26800', 'Électronique', 'Électronique', 'Batteries externes',
 480, 480, 59.00, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80', 'Batterie externe Anker PowerCore 26800 mAh noire avec câbles', 4.7, 567,
 true, 'achat', 'P033', '16×7×3 cm', 'Polycarbonate', '18 mois constructeur',
 'La PowerCore 26800 est la batterie externe de référence pour les longs voyages. Sa capacité de 26800 mAh permet de recharger un smartphone 6-7 fois.',
 '["Grande capacité","Charge rapide","Fiable","Prix abordable"]'::jsonb,
 '["Lourde","Pas autorisée en soute avion","Recharge lente"]'::jsonb,
 'P035', 'P034', true, true,
 8.5, 9.0, 8.5, 'Wirecutter 2025',
 83, 'Recommandé', 9.0, false,
 7.0, '["Tour du monde","Backpacking","Voyage"]'::jsonb, '["Tous"]'::jsonb,
 'Indispensable pour les voyages longs sans accès électrique régulier.'),

('anker-powercore-10000', 'Anker PowerCore 10000', 'Anker', 'PowerCore 10000', 'Électronique', 'Électronique', 'Batteries externes',
 180, 180, 29.00, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80', 'Batterie externe Anker PowerCore 10000 mAh noire compacte légère', 4.6, 789,
 true, 'achat', 'P034', '9×6×2 cm', 'Polycarbonate', '18 mois constructeur',
 'La PowerCore 10000 est la batterie externe compacte idéale pour les voyageurs légers. Légère et abordable, elle recharge un smartphone 2-3 fois.',
 '["Très légère","Compacte","Prix abordable","Autorisée cabine"]'::jsonb,
 '["Capacité limitée","Charge lente"]'::jsonb,
 'P033', NULL, true, true,
 8.0, 9.5, 8.0, 'Wirecutter 2025',
 79, 'Recommandé', 9.5, true,
 7.0, '["Backpacking","Trek","Voyage léger"]'::jsonb, '["Tous"]'::jsonb,
 'Parfait pour les voyageurs minimalistes. Autorisée en cabine avion.'),

('goal-zero-nomad-20', 'Goal Zero Nomad 20', 'Goal Zero', 'Nomad 20', 'Électronique', 'Électronique', 'Panneaux solaires',
 453, 453, 99.00, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80', 'Panneau solaire pliable Goal Zero Nomad 20 watts vert accroché sac', 4.5, 178,
 true, 'achat', 'P035', '25×20 cm (plié)', 'Monocristallin', '1 an constructeur',
 'Le Nomad 20 est le panneau solaire portable de référence pour les aventuriers. Ses 20 watts permettent de recharger smartphones et batteries en autonomie complète.',
 '["Autonomie solaire","Léger","Pliable","Compatible USB"]'::jsonb,
 '["Dépend de l''ensoleillement","Recharge lente","Prix élevé"]'::jsonb,
 NULL, 'P034', true, true,
 8.0, 7.5, 8.0, 'Goal Zero Official 2025',
 75, 'Confort', 7.5, false,
 7.0, '["Expédition","Trek long","Van Life"]'::jsonb, '["Ensoleillé","Désert","Tropical"]'::jsonb,
 'Pour les expéditions longues en zone ensoleillée. Inutile en forêt dense.'),

-- ── ACCESSOIRES ───────────────────────────────────────────────────────────────
('sea-to-summit-ultra-sil-nano', 'Sea to Summit Ultra-Sil Nano', 'Sea to Summit', 'Ultra-Sil Nano', 'Accessoires', 'Accessoires', 'Sacs étanches',
 31, 31, 29.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac étanche Sea to Summit Ultra-Sil Nano 20L bleu ultraléger', 4.7, 234,
 true, 'achat', 'P036', '20L capacité', 'Silnylon 15D', '2 ans constructeur',
 'L''Ultra-Sil Nano est le sac étanche ultraléger de référence. Ses 31g pour 20L de protection étanche en font l''accessoire indispensable pour protéger son matériel.',
 '["Ultra léger","Étanche","Compact","Polyvalent"]'::jsonb,
 '["Tissu délicat","Pas de fermeture éclair"]'::jsonb,
 NULL, NULL, true, true,
 8.5, 9.0, 7.5, 'OutdoorGearLab 2025',
 82, 'Recommandé', 9.5, true,
 6.0, '["Trek","Backpacking","Kayak","Tour du monde"]'::jsonb, '["Pluvieux","Tropical","Tous"]'::jsonb,
 'Indispensable pour protéger les affaires sensibles. Léger et fiable.'),

('osprey-ultralight-raincover', 'Osprey Ultralight Raincover', 'Osprey', 'Ultralight Raincover', 'Accessoires', 'Accessoires', 'Housses de pluie',
 85, 85, 29.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Housse de pluie Osprey Ultralight pour sac à dos jaune imperméable', 4.6, 189,
 true, 'achat', 'P037', 'S/M/L/XL', 'Nylon 40D', '2 ans constructeur',
 'La housse de pluie Ultralight d''Osprey est la protection indispensable pour votre sac à dos. Légère et compacte, elle se range dans une poche intégrée.',
 '["Légère","Compacte","Haute visibilité","Facile à mettre"]'::jsonb,
 '["Protection partielle","Taille à bien choisir"]'::jsonb,
 NULL, NULL, true, true,
 8.0, 9.0, 8.0, 'Osprey Official 2025',
 78, 'Recommandé', 9.0, true,
 7.0, '["Trek","Backpacking","Randonnée"]'::jsonb, '["Pluvieux","Montagne"]'::jsonb,
 'Indispensable pour les treks en zone pluvieuse. Protège le contenu du sac.'),

('black-diamond-trekking-poles', 'Black Diamond Trail Ergo Cork', 'Black Diamond', 'Trail Ergo Cork', 'Accessoires', 'Accessoires', 'Bâtons de randonnée',
 490, 490, 89.00, 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80', 'Bâtons de randonnée Black Diamond Trail Ergo Cork en aluminium paire', 4.7, 312,
 true, 'achat', 'P038', '64-140 cm réglable', 'Aluminium 7075', '3 ans constructeur',
 'Les Trail Ergo Cork sont les bâtons de randonnée de référence. Leur poignée en liège ergonomique et leur légèreté en font le choix des randonneurs exigeants.',
 '["Poignée liège ergonomique","Légers","Réglables","Robustes"]'::jsonb,
 '["Prix moyen","Pas pliables"]'::jsonb,
 'P039', NULL, true, true,
 8.5, 8.5, 9.0, 'OutdoorGearLab 2025',
 82, 'Recommandé', 8.0, false,
 8.5, '["Trek","Randonnée","Backpacking"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Recommandé pour les treks de plusieurs jours. Réduit la fatigue des genoux.'),

('leki-micro-vario-carbon', 'Leki Micro Vario Carbon', 'Leki', 'Micro Vario Carbon', 'Accessoires', 'Accessoires', 'Bâtons de randonnée',
 248, 248, 199.00, 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80', 'Bâtons de randonnée Leki Micro Vario Carbon pliables ultralégers noirs', 4.8, 178,
 true, 'achat', 'P039', '110-130 cm réglable', 'Carbone HTS 7.0', '3 ans constructeur',
 'Les Micro Vario Carbon sont les bâtons de randonnée ultralégers de référence. Leur construction en carbone et leur système de pliage en font le choix des ultralight hikers.',
 '["Ultra légers","Pliables","Carbone","Compact en sac"]'::jsonb,
 '["Prix très élevé","Moins robustes que l''aluminium"]'::jsonb,
 NULL, 'P038', true, true,
 9.0, 6.0, 8.0, 'Leki Official 2025',
 83, 'Recommandé', 8.5, true,
 7.0, '["Trek ultralight","Trail running","Backpacking"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Pour les ultralight hikers. Investissement premium justifié.'),

-- ── PRODUITS SUPPLÉMENTAIRES (P040-P081) ─────────────────────────────────────
('buff-merino-wool', 'Buff Merino Wool', 'Buff', 'Merino Wool', 'Accessoires', 'Accessoires', 'Accessoires tête',
 45, 45, 29.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Tour de cou Buff Merino Wool bleu multifonction laine mérinos', 4.7, 456,
 true, 'achat', 'P040', 'Taille unique', 'Laine mérinos 100%', '2 ans constructeur',
 'Le Buff Merino Wool est l''accessoire multifonction indispensable. Tour de cou, bonnet, cagoule, bandeau : 12 façons de le porter pour toutes les conditions.',
 '["Multifonction","Anti-odeur","Chaud","Léger"]'::jsonb,
 '["Séchage lent","Prix moyen"]'::jsonb,
 NULL, NULL, true, true,
 8.5, 9.0, 8.0, 'Buff Official 2025',
 82, 'Recommandé', 10.0, true,
 8.0, '["Trek","Tour du monde","Backpacking","Tous"]'::jsonb, '["Tous"]'::jsonb,
 'Accessoire indispensable pour sa polyvalence. Rapport poids/utilité exceptionnel.'),

('patagonia-nano-puff', 'Patagonia Nano Puff', 'Patagonia', 'Nano Puff', 'Vêtements', 'Vêtements', 'Doudounes',
 312, 312, 249.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Doudoune Patagonia Nano Puff bleue légère compressible', 4.8, 345,
 true, 'achat', 'P041', 'XS-XXL', 'PrimaLoft Gold Insulation', '2 ans constructeur',
 'La Nano Puff est la doudoune de référence pour les voyageurs. Légère, compressible et résistante à l''humidité, elle s''adapte à toutes les conditions.',
 '["Résistante à l''humidité","Légère","Compressible","Éco-responsable"]'::jsonb,
 '["Moins chaude que duvet","Prix élevé"]'::jsonb,
 'P042', NULL, true, true,
 9.0, 7.5, 8.5, 'OutdoorGearLab 2025',
 86, 'Recommandé', 9.0, true,
 8.0, '["Trek","Tour du monde","Backpacking","Voyage"]'::jsonb, '["Tempéré","Montagne","Arctique"]'::jsonb,
 'La doudoune polyvalente par excellence. Résiste à l''humidité contrairement au duvet.'),

('arc-teryx-cerium-lt', 'Arc''teryx Cerium LT', 'Arc''teryx', 'Cerium LT', 'Vêtements', 'Vêtements', 'Doudounes',
 290, 290, 399.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Doudoune Arc teryx Cerium LT grise duvet premium ultraléger', 4.9, 167,
 true, 'achat', 'P042', 'XS-XXL', 'Duvet 850 cuin', '2 ans constructeur',
 'La Cerium LT est la doudoune premium d''Arc''teryx. Son duvet 850 cuin et sa coupe technique en font la doudoune la plus chaude pour son poids.',
 '["Duvet 850 cuin","Ultra légère","Très chaude","Qualité premium"]'::jsonb,
 '["Prix très élevé","Sensible à l''humidité","Entretien spécifique"]'::jsonb,
 NULL, 'P041', true, true,
 10.0, 5.0, 9.0, 'OutdoorGearLab 2025',
 85, 'Confort', 8.0, true,
 8.5, '["Trek","Alpinisme","Expédition"]'::jsonb, '["Montagne","Arctique"]'::jsonb,
 'La meilleure doudoune légère du marché. Pour les conditions froides extrêmes.'),

('hydrapak-stow-1l', 'Hydrapak Stow 1L', 'Hydrapak', 'Stow 1L', 'Eau', 'Eau', 'Gourdes',
 38, 38, 19.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Gourde souple Hydrapak Stow 1 litre bleue pliable légère', 4.6, 345,
 true, 'achat', 'P043', '1L capacité', 'TPU sans BPA', '2 ans constructeur',
 'La Stow 1L est la gourde souple de référence pour les voyageurs. Légère, pliable et sans BPA, elle se range dans une poche quand elle est vide.',
 '["Ultra légère","Pliable","Sans BPA","Compacte vide"]'::jsonb,
 '["Moins durable que rigide","Nettoyage difficile"]'::jsonb,
 'P044', NULL, true, true,
 8.0, 9.5, 7.5, 'OutdoorGearLab 2025',
 80, 'Recommandé', 9.5, true,
 6.0, '["Trek","Backpacking","Tour du monde"]'::jsonb, '["Tous"]'::jsonb,
 'Parfait pour les voyageurs minimalistes. Se range dans une poche.'),

('nalgene-wide-mouth-1l', 'Nalgene Wide Mouth 1L', 'Nalgene', 'Wide Mouth 1L', 'Eau', 'Eau', 'Gourdes',
 180, 180, 14.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Gourde Nalgene Wide Mouth 1 litre transparente incassable', 4.7, 678,
 true, 'achat', 'P044', '1L capacité', 'Tritan sans BPA', '2 ans constructeur',
 'La Nalgene Wide Mouth est la gourde indestructible de référence. Sa large ouverture facilite le remplissage et le nettoyage, et elle résiste à tout.',
 '["Indestructible","Large ouverture","Sans BPA","Prix abordable"]'::jsonb,
 '["Lourde","Pas compressible","Volumineuse"]'::jsonb,
 'P043', NULL, true, true,
 8.0, 10.0, 10.0, 'Wirecutter 2025',
 78, 'Recommandé', 9.0, true,
 10.0, '["Camping","Trek","Backpacking"]'::jsonb, '["Tous"]'::jsonb,
 'La gourde pour la vie. Indestructible et abordable.'),

('black-diamond-distance-carbon-z', 'Black Diamond Distance Carbon Z', 'Black Diamond', 'Distance Carbon Z', 'Accessoires', 'Accessoires', 'Bâtons trail',
 218, 218, 169.00, 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80', 'Bâtons trail running Black Diamond Distance Carbon Z pliables noirs', 4.7, 189,
 true, 'achat', 'P045', '100-125 cm', 'Carbone', '3 ans constructeur',
 'Les Distance Carbon Z sont les bâtons de trail running de référence. Leur pliage en Z et leur légèreté en font le choix des coureurs de montagne.',
 '["Ultra légers","Pliage Z rapide","Carbone","Compact"]'::jsonb,
 '["Prix élevé","Moins robustes","Pas réglables"]'::jsonb,
 NULL, 'P038', true, true,
 9.0, 6.5, 8.0, 'iRunFar 2025',
 80, 'Recommandé', 7.5, true,
 7.0, '["Trail running","Trek rapide"]'::jsonb, '["Montagne"]'::jsonb,
 'Pour les trail runners et randonneurs rapides. Pliage Z ultra-rapide.'),

('patagonia-baggies-shorts', 'Patagonia Baggies Shorts', 'Patagonia', 'Baggies Shorts', 'Vêtements', 'Vêtements', 'Shorts',
 145, 145, 65.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Short Patagonia Baggies bleu séchage rapide polyvalent voyage', 4.7, 456,
 true, 'achat', 'P046', 'XS-XXL', 'Nylon recyclé 100%', '2 ans constructeur',
 'Les Baggies Shorts sont le short de voyage par excellence. Séchage rapide, polyvalent (plage, randonnée, ville) et éco-responsable, ils s''adaptent à toutes les situations.',
 '["Séchage rapide","Polyvalent","Éco-responsable","Léger"]'::jsonb,
 '["Pas de poches zippées","Pas idéal pour trek technique"]'::jsonb,
 NULL, NULL, true, true,
 8.5, 8.5, 8.0, 'Patagonia Official 2025',
 83, 'Recommandé', 10.0, true,
 8.0, '["Tour du monde","Backpacking","Plage","Randonnée"]'::jsonb, '["Tropical","Tempéré"]'::jsonb,
 'Le short de voyage idéal. Polyvalent et éco-responsable.'),

('columbia-silver-ridge-shirt', 'Columbia Silver Ridge Shirt', 'Columbia', 'Silver Ridge', 'Vêtements', 'Vêtements', 'Chemises',
 198, 198, 55.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Chemise Columbia Silver Ridge bleue anti-UV séchage rapide', 4.5, 345,
 true, 'achat', 'P047', 'S-XXL', 'Nylon Omni-Wick', '2 ans constructeur',
 'La Silver Ridge est la chemise de voyage de référence. Sa protection UPF 50+ et son séchage rapide en font le choix des voyageurs en zone ensoleillée.',
 '["UPF 50+","Séchage rapide","Légère","Poches pratiques"]'::jsonb,
 '["Pas très respirante","Style basique"]'::jsonb,
 NULL, NULL, true, true,
 8.0, 9.0, 8.0, 'Columbia Official 2025',
 79, 'Recommandé', 9.0, true,
 8.0, '["Tour du monde","Backpacking","Voyage tropical"]'::jsonb, '["Tropical","Désert","Ensoleillé"]'::jsonb,
 'Indispensable pour les voyages en zone ensoleillée. Protection UV efficace.'),

('exped-downmat-ul-7', 'Exped DownMat UL 7', 'Exped', 'DownMat UL 7', 'Couchage', 'Couchage', 'Matelas',
 595, 595, 249.00, 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=600&q=80', 'Matelas gonflable Exped DownMat UL 7 orange avec duvet R-value 7', 4.8, 134,
 true, 'achat', 'P048', '183×52×9 cm', 'Nylon 20D, duvet 700 cuin', '2 ans constructeur',
 'Le DownMat UL 7 est le matelas 4 saisons de référence. Son R-value de 7 et son duvet intégré en font le choix pour les conditions hivernales.',
 '["R-value 7 excellent","Duvet intégré","Confort hivernal","Léger pour sa chaleur"]'::jsonb,
 '["Prix très élevé","Sensible à l''humidité","Gonflage complexe"]'::jsonb,
 NULL, 'P009', true, true,
 9.5, 5.5, 8.5, 'OutdoorGearLab 2025',
 83, 'Recommandé', 7.0, false,
 6.5, '["Expédition hivernale","Trek 4 saisons"]'::jsonb, '["Arctique","Montagne","Hiver"]'::jsonb,
 'Pour les conditions hivernales extrêmes. Overkill pour l''été.'),

('msr-pocket-rocket-deluxe', 'MSR PocketRocket Deluxe', 'MSR', 'PocketRocket Deluxe', 'Cuisine', 'Cuisine', 'Réchauds',
 73, 73, 59.00, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', 'Réchaud MSR PocketRocket Deluxe ultraléger avec régulateur pression', 4.7, 289,
 true, 'achat', 'P049', '6×4 cm (rangé)', 'Acier inox', '2 ans constructeur',
 'Le PocketRocket Deluxe est le réchaud ultraléger de référence. Son régulateur de pression maintient une flamme constante même par temps froid.',
 '["Ultra léger","Régulateur pression","Compact","Compatible toutes cartouches"]'::jsonb,
 '["Pas de casserole incluse","Moins stable que WindBurner"]'::jsonb,
 'P027', NULL, true, true,
 8.5, 9.0, 8.5, 'OutdoorGearLab 2025',
 84, 'Recommandé', 8.5, true,
 8.5, '["Trek","Backpacking","Camping"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Meilleur réchaud ultraléger du marché. Idéal pour les randonneurs minimalistes.'),

('sea-to-summit-x-pot', 'Sea to Summit X-Pot 2.8L', 'Sea to Summit', 'X-Pot 2.8L', 'Cuisine', 'Cuisine', 'Casseroles',
 290, 290, 79.00, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', 'Casserole pliable Sea to Summit X-Pot 2.8L rouge silicone', 4.6, 167,
 true, 'achat', 'P050', '19×19×9 cm (déplié)', 'Aluminium, silicone', '2 ans constructeur',
 'La X-Pot est la casserole pliable de référence. Son fond en aluminium et ses parois en silicone permettent de la comprimer à 4cm de hauteur.',
 '["Pliable","Légère","Grande capacité","Polyvalente"]'::jsonb,
 '["Parois silicone fragiles","Nettoyage difficile"]'::jsonb,
 NULL, NULL, true, true,
 8.0, 8.5, 7.5, 'OutdoorGearLab 2025',
 78, 'Recommandé', 8.0, false,
 6.0, '["Trek groupe","Camping","Backpacking"]'::jsonb, '["Tous"]'::jsonb,
 'Idéal pour cuisiner pour 2-4 personnes en trek. Gain de place remarquable.'),

('osprey-daylite-plus', 'Osprey Daylite Plus 20', 'Osprey', 'Daylite Plus 20', 'Sacs à dos', 'Sacs à dos', 'Sacs de jour',
 510, 510, 79.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac à dos Osprey Daylite Plus 20 litres gris sac de jour', 4.6, 234,
 true, 'achat', 'P051', '50×28×18 cm', 'Nylon 210D', '2 ans constructeur',
 'Le Daylite Plus est le sac de jour idéal pour les excursions depuis un camp de base. Compatible avec les sacs Osprey, il se fixe en façade pour les grandes randonnées.',
 '["Compatible sacs Osprey","Léger","Polyvalent","Poche laptop"]'::jsonb,
 '["Pas de ceinture lombaire","Volume limité"]'::jsonb,
 NULL, 'P002', true, true,
 8.0, 9.0, 8.0, 'Osprey Official 2025',
 78, 'Recommandé', 8.5, true,
 8.0, '["Trek","Randonnée journée","Voyage urbain"]'::jsonb, '["Tous"]'::jsonb,
 'Parfait comme sac de jour lors d''un trek avec camp de base.'),

('patagonia-black-hole-duffel-55', 'Patagonia Black Hole Duffel 55L', 'Patagonia', 'Black Hole Duffel 55L', 'Sacs à dos', 'Sacs à dos', 'Sacs de voyage',
 680, 680, 149.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac de voyage Patagonia Black Hole Duffel 55L noir imperméable', 4.8, 289,
 true, 'achat', 'P052', '55L capacité', 'Nylon recyclé 100%', '2 ans constructeur',
 'Le Black Hole Duffel est le sac de voyage polyvalent de référence. Utilisable en sac à dos ou en sac de sport, il est imperméable et éco-responsable.',
 '["Imperméable","Polyvalent","Éco-responsable","Robuste"]'::jsonb,
 '["Lourd","Pas de cadre","Accès unique"]'::jsonb,
 NULL, 'P001', true, true,
 8.5, 8.0, 9.0, 'OutdoorGearLab 2025',
 80, 'Recommandé', 8.0, false,
 8.5, '["Voyage","Tour du monde","Camping","Van Life"]'::jsonb, '["Tous"]'::jsonb,
 'Excellent sac de voyage polyvalent. Idéal pour les voyages mixtes.'),

('black-diamond-momentum-harness', 'Black Diamond Momentum Harness', 'Black Diamond', 'Momentum', 'Sécurité', 'Sécurité', 'Harnais',
 340, 340, 59.00, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', 'Baudrier escalade Black Diamond Momentum rouge réglable débutant', 4.7, 234,
 true, 'achat', 'P053', 'XS-XL', 'Nylon, mousse EVA', '2 ans constructeur',
 'Le Momentum est le baudrier d''initiation de référence. Confortable et facile à régler, il convient parfaitement aux débutants en escalade.',
 '["Confortable","Facile à régler","Léger","Prix abordable"]'::jsonb,
 '["Pas pour alpinisme","Moins performant que harnais techniques"]'::jsonb,
 'P032', NULL, true, true,
 8.0, 9.0, 8.0, 'Black Diamond Official 2025',
 75, 'Recommandé', 5.0, false,
 8.5, '["Escalade","Via ferrata"]'::jsonb, '["Falaise","Montagne"]'::jsonb,
 'Parfait pour débuter l''escalade. Inutile pour le trek classique.'),

('petzl-sitta-harness', 'Petzl Sitta Harness', 'Petzl', 'Sitta', 'Sécurité', 'Sécurité', 'Harnais',
 280, 280, 119.00, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', 'Baudrier escalade Petzl Sitta noir léger performance', 4.8, 156,
 true, 'achat', 'P054', 'S-XL', 'Nylon, Dyneema', '2 ans constructeur',
 'Le Sitta est le baudrier performance de Petzl. Ultra léger et confortable, il convient aux grimpeurs confirmés qui cherchent légèreté et performance.',
 '["Ultra léger","Confortable","Performance","Réglage précis"]'::jsonb,
 '["Prix élevé","Moins confortable pour débutants"]'::jsonb,
 NULL, 'P053', true, true,
 9.0, 7.0, 9.0, 'Petzl Official 2025',
 78, 'Recommandé', 5.0, false,
 8.5, '["Escalade","Alpinisme"]'::jsonb, '["Falaise","Montagne"]'::jsonb,
 'Pour les grimpeurs confirmés. Légèreté et performance au rendez-vous.'),

('mammut-crag-sender-helmet', 'Mammut Crag Sender Helmet', 'Mammut', 'Crag Sender', 'Sécurité', 'Sécurité', 'Casques',
 195, 195, 89.00, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', 'Casque escalade Mammut Crag Sender blanc léger ventilé', 4.7, 178,
 true, 'achat', 'P055', '52-61 cm', 'Polycarbonate, EPS', '2 ans constructeur',
 'Le Crag Sender est le casque d''escalade polyvalent de Mammut. Léger et bien ventilé, il convient aussi bien à l''escalade sportive qu''à l''alpinisme.',
 '["Léger","Bien ventilé","Polyvalent","Confortable"]'::jsonb,
 '["Moins résistant que casques intégraux","Pas pour ski"]'::jsonb,
 NULL, NULL, true, true,
 8.5, 8.5, 8.5, 'Mammut Official 2025',
 78, 'Recommandé', 5.5, false,
 8.0, '["Escalade","Alpinisme","Via ferrata"]'::jsonb, '["Montagne","Falaise"]'::jsonb,
 'Bon casque polyvalent pour l''escalade et l''alpinisme léger.'),

('black-diamond-camalot-c4', 'Black Diamond Camalot C4', 'Black Diamond', 'Camalot C4', 'Sécurité', 'Sécurité', 'Protection escalade',
 120, 120, 69.00, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', 'Coinceur Black Diamond Camalot C4 rouge pour escalade en fissure', 4.9, 234,
 true, 'achat', 'P056', 'Taille 0.5', 'Aluminium', '2 ans constructeur',
 'Le Camalot C4 est le coinceur mécanique de référence mondiale. Sa fiabilité légendaire et sa large plage de taille en font l''incontournable de l''escalade en fissure.',
 '["Fiabilité légendaire","Large plage","Léger","Standard industrie"]'::jsonb,
 '["Prix élevé","Spécifique escalade fissure"]'::jsonb,
 NULL, NULL, true, true,
 10.0, 7.0, 10.0, 'Black Diamond Official 2025',
 75, 'Confort', 3.0, false,
 9.5, '["Escalade grande voie","Big wall"]'::jsonb, '["Falaise","Montagne"]'::jsonb,
 'Pour les grimpeurs en fissure. Inutile pour le trek ou l''escalade sportive.'),

('rab-microlight-alpine-jacket', 'Rab Microlight Alpine Jacket', 'Rab', 'Microlight Alpine', 'Vêtements', 'Vêtements', 'Doudounes',
 350, 350, 279.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Doudoune Rab Microlight Alpine bleue duvet 750 cuin légère', 4.7, 189,
 true, 'achat', 'P057', 'XS-XXL', 'Duvet 750 cuin', '2 ans constructeur',
 'La Microlight Alpine est la doudoune polyvalente de Rab. Son duvet 750 cuin et sa coupe alpine en font un excellent compromis entre légèreté et chaleur.',
 '["Duvet 750 cuin","Légère","Coupe alpine","Rapport Q/P"]'::jsonb,
 '["Sensible à l''humidité","Moins chaude que Cerium"]'::jsonb,
 'P042', 'P041', true, true,
 8.5, 8.0, 8.5, 'OutdoorGearLab 2025',
 82, 'Recommandé', 8.0, true,
 8.0, '["Trek","Alpinisme","Voyage"]'::jsonb, '["Montagne","Tempéré froid"]'::jsonb,
 'Excellent compromis qualité/prix en doudoune duvet.'),

('mountain-hardwear-ghost-whisperer', 'Mountain Hardwear Ghost Whisperer', 'Mountain Hardwear', 'Ghost Whisperer', 'Vêtements', 'Vêtements', 'Doudounes',
 227, 227, 349.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'Doudoune Mountain Hardwear Ghost Whisperer grise ultra légère 800 cuin', 4.8, 145,
 true, 'achat', 'P058', 'XS-XXL', 'Duvet 800 cuin', '2 ans constructeur',
 'La Ghost Whisperer est la doudoune ultraléger de référence. Ses 227g pour une chaleur exceptionnelle en font le choix des alpinistes et randonneurs exigeants.',
 '["Ultra légère","Duvet 800 cuin","Compressible","Haute performance"]'::jsonb,
 '["Prix très élevé","Tissu délicat","Sensible à l''humidité"]'::jsonb,
 'P042', 'P057', true, true,
 9.5, 5.5, 8.0, 'OutdoorGearLab 2025',
 84, 'Confort', 7.5, true,
 7.0, '["Alpinisme","Trek","Expédition"]'::jsonb, '["Montagne","Arctique"]'::jsonb,
 'Pour les puristes du poids. La doudoune la plus légère de sa catégorie.'),

('osprey-ultralight-stuff-pack', 'Osprey Ultralight Stuff Pack', 'Osprey', 'Ultralight Stuff Pack', 'Sacs à dos', 'Sacs à dos', 'Sacs pliables',
 113, 113, 39.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac à dos pliable Osprey Ultralight Stuff Pack 18L bleu', 4.5, 178,
 true, 'achat', 'P059', '18L capacité', 'Nylon 30D', '2 ans constructeur',
 'L''Ultralight Stuff Pack est le sac de jour pliable de référence. Il se range dans sa propre poche et pèse seulement 113g, parfait comme sac de secours.',
 '["Ultra léger","Pliable","Compact","Prix abordable"]'::jsonb,
 '["Pas de ceinture","Bretelles fines","Volume limité"]'::jsonb,
 NULL, NULL, true, true,
 7.5, 9.5, 7.0, 'Osprey Official 2025',
 75, 'Recommandé', 9.0, true,
 6.0, '["Voyage","Tour du monde","Randonnée journée"]'::jsonb, '["Tous"]'::jsonb,
 'Parfait comme sac de secours ou sac de jour léger. Indispensable en voyage.'),

('lifestraw-personal', 'LifeStraw Personal', 'LifeStraw', 'Personal', 'Eau', 'Eau', 'Filtration',
 42, 42, 19.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Filtre à eau LifeStraw Personal bleu boire directement source', 4.5, 567,
 true, 'achat', 'P060', '22×2.5 cm', 'Fibre creuse 0.2 micron', '2 ans constructeur',
 'Le LifeStraw Personal est le filtre à eau le plus simple et le moins cher du marché. Boire directement depuis une source en quelques secondes.',
 '["Très léger","Prix abordable","Simple d''utilisation","Longue durée"]'::jsonb,
 '["Ne filtre pas les virus","Boire directement uniquement","Pas de réservoir"]'::jsonb,
 'P014', NULL, true, true,
 7.5, 10.0, 8.0, 'OutdoorGearLab 2025',
 75, 'Recommandé', 8.5, true,
 7.5, '["Trek","Camping","Randonnée"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Le filtre le moins cher du marché. Idéal comme backup ou pour les budgets serrés.'),

('aquatabs-water-purification', 'Aquatabs Water Purification', 'Aquatabs', 'Water Purification Tablets', 'Eau', 'Eau', 'Purification chimique',
 15, 15, 9.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Pastilles purification eau Aquatabs boite 50 comprimés', 4.4, 234,
 true, 'achat', 'P061', 'Boite 50 comprimés', 'Chlore NaDCC', '3 ans (date péremption)',
 'Les Aquatabs sont les pastilles de purification d''eau de référence. Légères et abordables, elles éliminent bactéries et virus en 30 minutes.',
 '["Ultra légères","Éliminent virus","Prix abordable","Longue conservation"]'::jsonb,
 '["Goût chloré","Attente 30 min","Pas pour eau très turbide"]'::jsonb,
 'P016', 'P014', true, true,
 7.0, 10.0, 9.0, 'WHO Approved',
 72, 'Recommandé', 9.5, true,
 10.0, '["Voyage tropical","Expédition","Trek zones à risque"]'::jsonb, '["Tropical","Désert","Tous"]'::jsonb,
 'Backup indispensable pour les zones à risque viral. Léger et efficace.'),

('garmin-fenix-7', 'Garmin Fenix 7 Solar', 'Garmin', 'Fenix 7 Solar', 'Électronique', 'Électronique', 'Montres GPS',
 79, 79, 799.00, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80', 'Montre GPS Garmin Fenix 7 Solar noire avec recharge solaire', 4.9, 345,
 true, 'achat', 'P062', '47mm diamètre', 'Fibre de verre, verre saphir', '1 an constructeur',
 'La Fenix 7 Solar est la montre GPS premium de Garmin avec recharge solaire. Sa batterie quasi-illimitée en mode solaire en fait le choix des expéditions longues.',
 '["Recharge solaire","Batterie 28 jours","Cartes topo","Multi-sport"]'::jsonb,
 '["Prix très élevé","Lourde","Interface complexe"]'::jsonb,
 'P019', NULL, true, true,
 9.5, 4.5, 9.5, 'DC Rainmaker 2025',
 85, 'Luxe', 8.5, true,
 8.5, '["Expédition","Trek","Trail running","Tour du monde"]'::jsonb, '["Tous"]'::jsonb,
 'La montre GPS ultime pour les expéditions longues. Luxe justifié pour les aventuriers.'),

('apple-airtag', 'Apple AirTag', 'Apple', 'AirTag', 'Électronique', 'Électronique', 'Trackers',
 11, 11, 35.00, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80', 'Apple AirTag blanc tracker GPS pour bagages et objets', 4.6, 678,
 true, 'achat', 'P063', '3.2 cm diamètre', 'Acier inox, polycarbonate', '1 an constructeur',
 'L''AirTag est le tracker de bagages de référence pour les utilisateurs Apple. Glissé dans votre sac, il permet de localiser vos bagages perdus en temps réel.',
 '["Très léger","Réseau Find My","Précis","Batterie 1 an"]'::jsonb,
 '["Écosystème Apple uniquement","Pas de GPS autonome","Abonnement iCloud"]'::jsonb,
 NULL, NULL, true, true,
 8.0, 9.0, 8.0, 'Wirecutter 2025',
 72, 'Confort', 9.5, true,
 7.0, '["Tour du monde","Voyage avion","Backpacking"]'::jsonb, '["Tous"]'::jsonb,
 'Indispensable pour les voyageurs Apple. Protège contre la perte de bagages.'),

('tile-mate-2022', 'Tile Mate 2022', 'Tile', 'Mate 2022', 'Électronique', 'Électronique', 'Trackers',
 8, 8, 25.00, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80', 'Tracker Tile Mate 2022 blanc carré pour bagages Android iOS', 4.4, 345,
 true, 'achat', 'P064', '3.4×3.4 cm', 'Polycarbonate', '1 an constructeur',
 'Le Tile Mate est le tracker de bagages compatible Android et iOS. Alternative à l''AirTag, il fonctionne sur tous les smartphones.',
 '["Compatible Android","Prix abordable","Réseau Tile","Sonnerie"]'::jsonb,
 '["Réseau moins dense qu''Apple","Batterie non remplaçable"]'::jsonb,
 'P063', NULL, true, true,
 7.5, 9.5, 7.5, 'Wirecutter 2025',
 68, 'Confort', 9.0, true,
 6.0, '["Tour du monde","Voyage avion"]'::jsonb, '["Tous"]'::jsonb,
 'Alternative Android à l''AirTag. Moins précis mais compatible tous smartphones.'),

('sea-to-summit-aeros-pillow', 'Sea to Summit Aeros Pillow', 'Sea to Summit', 'Aeros Pillow', 'Couchage', 'Couchage', 'Oreillers',
 67, 67, 39.00, 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=600&q=80', 'Oreiller gonflable Sea to Summit Aeros Pillow bleu compact léger', 4.6, 289,
 true, 'achat', 'P065', '40×28 cm (gonflé)', 'Nylon 20D, TPU', '2 ans constructeur',
 'L''Aeros Pillow est l''oreiller de camping de référence. Léger, compact et confortable, il améliore considérablement la qualité du sommeil en bivouac.',
 '["Très léger","Compact","Confortable","Valve pratique"]'::jsonb,
 '["Prix élevé pour un oreiller","Peut glisser"]'::jsonb,
 NULL, NULL, true, true,
 8.5, 8.0, 8.0, 'OutdoorGearLab 2025',
 78, 'Recommandé', 9.5, true,
 7.0, '["Trek","Camping","Backpacking","Tour du monde"]'::jsonb, '["Tous"]'::jsonb,
 'Améliore significativement le sommeil en bivouac. Petit luxe justifié.'),

('cocoon-travel-sheet', 'Cocoon Travel Sheet', 'Cocoon', 'Travel Sheet', 'Couchage', 'Couchage', 'Draps de voyage',
 125, 125, 45.00, 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=600&q=80', 'Drap de voyage Cocoon en soie naturelle blanc compact léger', 4.7, 234,
 true, 'achat', 'P066', '220×80 cm', 'Soie naturelle', '2 ans constructeur',
 'Le Cocoon Travel Sheet est le drap de voyage en soie de référence. Léger, compact et hygiénique, il est indispensable pour les auberges de jeunesse et les hébergements douteux.',
 '["Soie naturelle","Léger","Compact","Hygiénique"]'::jsonb,
 '["Prix élevé","Séchage lent","Délicat"]'::jsonb,
 NULL, NULL, true, true,
 8.5, 8.0, 7.5, 'Cocoon Official 2025',
 75, 'Recommandé', 9.5, true,
 7.0, '["Tour du monde","Backpacking","Auberges"]'::jsonb, '["Tropical","Tempéré"]'::jsonb,
 'Indispensable pour les auberges de jeunesse. Hygiène et confort garantis.'),

('patagonia-capilene-cool', 'Patagonia Capilene Cool Daily', 'Patagonia', 'Capilene Cool Daily', 'Vêtements', 'Vêtements', 'T-shirts techniques',
 120, 120, 55.00, 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80', 'T-shirt technique Patagonia Capilene Cool Daily bleu séchage rapide', 4.6, 345,
 true, 'achat', 'P067', 'XS-XXL', 'Polyester recyclé 100%', '2 ans constructeur',
 'Le Capilene Cool Daily est le t-shirt technique de référence de Patagonia. Séchage rapide, anti-odeur et éco-responsable, il convient à toutes les activités.',
 '["Séchage rapide","Anti-odeur","Éco-responsable","Léger"]'::jsonb,
 '["Moins chaud que mérinos","Pas aussi doux"]'::jsonb,
 'P022', NULL, true, true,
 8.0, 8.5, 8.0, 'Patagonia Official 2025',
 79, 'Recommandé', 9.5, true,
 7.5, '["Trek","Tour du monde","Backpacking","Sport"]'::jsonb, '["Tropical","Tempéré"]'::jsonb,
 'Excellent t-shirt technique éco-responsable. Alternative synthétique au mérinos.'),

('exped-fold-drybag', 'Exped Fold Drybag 20L', 'Exped', 'Fold Drybag 20L', 'Accessoires', 'Accessoires', 'Sacs étanches',
 89, 89, 25.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80', 'Sac étanche Exped Fold Drybag 20L orange avec fermeture roll-top', 4.6, 189,
 true, 'achat', 'P068', '20L capacité', 'Nylon 210D TPU', '2 ans constructeur',
 'Le Fold Drybag est le sac étanche polyvalent d''Exped. Sa fermeture roll-top et son matériau robuste en font un excellent choix pour protéger l''électronique et les vêtements.',
 '["Robuste","Étanche","Fermeture roll-top","Prix abordable"]'::jsonb,
 '["Plus lourd que Ultra-Sil","Moins compact"]'::jsonb,
 'P036', NULL, true, true,
 8.0, 9.5, 8.5, 'Exped Official 2025',
 78, 'Recommandé', 9.0, true,
 8.0, '["Trek","Kayak","Camping","Backpacking"]'::jsonb, '["Pluvieux","Tropical","Tous"]'::jsonb,
 'Bon sac étanche robuste pour un prix abordable. Idéal pour l''électronique.'),

('black-diamond-spot-325', 'Black Diamond Spot 325', 'Black Diamond', 'Spot 325', 'Éclairage', 'Éclairage', 'Frontales',
 88, 88, 29.00, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', 'Lampe frontale Black Diamond Spot 325 lumens rouge compacte', 4.4, 234,
 true, 'achat', 'P069', '7×4×3 cm', 'ABS', '3 ans constructeur',
 'La Spot 325 est la version économique de la Spot 400. Ses 325 lumens et son prix abordable en font un excellent choix pour les randonneurs débutants.',
 '["Prix abordable","325 lumens","IPX4","Piles AAA"]'::jsonb,
 '["Moins puissante que Spot 400","Pas rechargeable"]'::jsonb,
 'P012', NULL, true, true,
 7.5, 10.0, 8.0, 'Black Diamond Official 2025',
 72, 'Recommandé', 8.5, true,
 9.0, '["Randonnée","Camping","Trek débutant"]'::jsonb, '["Tous"]'::jsonb,
 'Excellent choix budget pour débuter. Fiable et abordable.'),

('msr-alpine-stowaway-pot', 'MSR Alpine Stowaway Pot 1.1L', 'MSR', 'Alpine Stowaway 1.1L', 'Cuisine', 'Cuisine', 'Casseroles',
 142, 142, 39.00, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', 'Casserole MSR Alpine Stowaway 1.1L acier inox légère', 4.7, 234,
 true, 'achat', 'P070', '14×9 cm', 'Acier inox 18/8', '2 ans constructeur',
 'La Alpine Stowaway est la casserole de randonnée de référence. Son acier inox 18/8 la rend indestructible et compatible avec tous les réchauds.',
 '["Indestructible","Compatible tous réchauds","Légère","Prix abordable"]'::jsonb,
 '["Pas de poignée isolante","Moins légère que titane"]'::jsonb,
 NULL, NULL, true, true,
 8.5, 9.5, 10.0, 'MSR Official 2025',
 80, 'Recommandé', 8.5, false,
 10.0, '["Trek","Camping","Backpacking"]'::jsonb, '["Tous"]'::jsonb,
 'La casserole pour la vie. Indestructible et polyvalente.'),

('sea-to-summit-alpha-pot', 'Sea to Summit Alpha Pot 1.2L', 'Sea to Summit', 'Alpha Pot 1.2L', 'Cuisine', 'Cuisine', 'Casseroles',
 155, 155, 59.00, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', 'Casserole Sea to Summit Alpha Pot 1.2L aluminium anodisé légère', 4.6, 167,
 true, 'achat', 'P071', '14×9 cm', 'Aluminium anodisé', '2 ans constructeur',
 'L''Alpha Pot est la casserole légère de référence de Sea to Summit. Son aluminium anodisé offre un excellent rapport légèreté/durabilité.',
 '["Légère","Aluminium anodisé","Bonne conductivité","Compact"]'::jsonb,
 '["Moins durable que inox","Rayures possibles"]'::jsonb,
 'P070', NULL, true, true,
 8.0, 8.5, 8.0, 'Sea to Summit Official 2025',
 77, 'Recommandé', 8.0, false,
 7.5, '["Trek","Backpacking","Camping"]'::jsonb, '["Tous"]'::jsonb,
 'Bon compromis légèreté/durabilité. Alternative légère à l''inox.'),

('platypus-platy-bottle-2l', 'Platypus Platy Bottle 2L', 'Platypus', 'Platy Bottle 2L', 'Eau', 'Eau', 'Gourdes',
 28, 28, 12.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Gourde souple Platypus Platy Bottle 2L transparente pliable légère', 4.5, 289,
 true, 'achat', 'P072', '2L capacité', 'Polyéthylène sans BPA', '2 ans constructeur',
 'La Platy Bottle est la gourde souple de référence pour les grandes capacités. Ses 28g pour 2L en font l''option la plus légère du marché.',
 '["Ultra légère","Grande capacité","Pliable","Prix abordable"]'::jsonb,
 '["Moins durable","Nettoyage difficile","Pas de bouchon sport"]'::jsonb,
 'P043', NULL, true, true,
 7.5, 10.0, 7.0, 'OutdoorGearLab 2025',
 72, 'Recommandé', 8.5, true,
 5.0, '["Trek","Camping","Backpacking"]'::jsonb, '["Tous"]'::jsonb,
 'La gourde la plus légère du marché. Parfait pour les grandes capacités.'),

('petzl-tikka-core', 'Petzl Tikka Core', 'Petzl', 'Tikka Core', 'Éclairage', 'Éclairage', 'Frontales',
 80, 80, 39.00, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', 'Lampe frontale Petzl Tikka Core noire 300 lumens rechargeable', 4.5, 345,
 true, 'achat', 'P073', '7×4×3 cm', 'ABS', '3 ans constructeur',
 'La Tikka Core est la frontale rechargeable d''entrée de gamme de Petzl. Ses 300 lumens et son prix abordable en font un excellent choix pour les randonneurs occasionnels.',
 '["Rechargeable","300 lumens","Légère","Prix abordable"]'::jsonb,
 '["Moins puissante que Actik","Faisceau basique"]'::jsonb,
 'P011', NULL, true, true,
 7.5, 9.5, 7.5, 'Petzl Official 2025',
 72, 'Recommandé', 8.5, true,
 8.0, '["Randonnée","Camping","Trek débutant"]'::jsonb, '["Tous"]'::jsonb,
 'Excellent choix budget rechargeable. Idéal pour débuter.'),

('osprey-hydraulics-3l', 'Osprey Hydraulics 3L Reservoir', 'Osprey', 'Hydraulics 3L', 'Eau', 'Eau', 'Poches à eau',
 175, 175, 39.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Poche à eau Osprey Hydraulics 3 litres avec tuyau et embout', 4.6, 234,
 true, 'achat', 'P074', '3L capacité', 'Polyéthylène sans BPA', '2 ans constructeur',
 'La poche Hydraulics 3L est la référence pour l''hydratation en mouvement. Compatible avec tous les sacs Osprey, elle permet de boire sans s''arrêter.',
 '["Boire en mouvement","3L capacité","Compatible Osprey","Facile à remplir"]'::jsonb,
 '["Nettoyage difficile","Risque de fuite","Lourd plein"]'::jsonb,
 NULL, NULL, true, true,
 8.0, 9.0, 7.5, 'Osprey Official 2025',
 75, 'Recommandé', 8.5, false,
 6.0, '["Trail running","Trek","Randonnée longue"]'::jsonb, '["Tous"]'::jsonb,
 'Indispensable pour les longues randonnées sans pause. Hydratation continue.'),

('black-diamond-helio-135', 'Black Diamond Helio 135 Tent', 'Black Diamond', 'Helio 135', 'Tentes', 'Tentes', 'Tentes ultralight',
 1080, 1080, 499.00, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80', 'Tente Black Diamond Helio 135 ultraléger 1 place orange', 4.6, 89,
 true, 'achat', 'P075', '213×91×97 cm', 'Nylon 10D Ripstop', '2 ans constructeur',
 'La Helio 135 est la tente ultraléger 1 place de Black Diamond. Son poids de 1080g et sa résistance aux intempéries en font un excellent choix pour les randonneurs solo.',
 '["Ultra légère","Résistante","1 place confortable","Bonne ventilation"]'::jsonb,
 '["Prix élevé","1 place uniquement","Montage complexe"]'::jsonb,
 'P005', 'P004', true, true,
 8.5, 7.0, 8.5, 'OutdoorGearLab 2025',
 80, 'Recommandé', 7.0, false,
 7.0, '["Trek solo","Backpacking","Expédition"]'::jsonb, '["Montagne","Tempéré"]'::jsonb,
 'Excellent choix pour les randonneurs solo. Légèreté et résistance au rendez-vous.'),

('msr-elixir-2', 'MSR Elixir 2', 'MSR', 'Elixir 2', 'Tentes', 'Tentes', '3 saisons',
 2100, 2100, 299.00, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80', 'Tente MSR Elixir 2 verte 2 places 3 saisons abordable', 4.5, 234,
 true, 'achat', 'P076', '213×127×97 cm', 'Nylon 68D', '2 ans constructeur',
 'La MSR Elixir 2 est la tente 2 places abordable de référence. Son rapport qualité/prix excellent et sa robustesse en font le choix idéal pour les campeurs débutants.',
 '["Prix abordable","Robuste","Facile à monter","Bonne protection"]'::jsonb,
 '["Lourde","Moins performante que Hubba Hubba","Ventilation limitée"]'::jsonb,
 'P004', NULL, true, true,
 8.0, 9.5, 8.5, 'OutdoorGearLab 2025',
 78, 'Recommandé', 7.5, false,
 8.5, '["Camping","Trek débutant","Backpacking"]'::jsonb, '["Tempéré","Montagne"]'::jsonb,
 'Meilleur rapport qualité/prix en tente 2 places. Idéal pour débuter.'),

('thermarest-z-lite-sol', 'Therm-a-Rest Z Lite Sol', 'Therm-a-Rest', 'Z Lite Sol', 'Couchage', 'Couchage', 'Matelas',
 410, 410, 59.00, 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=600&q=80', 'Matelas mousse Therm-a-Rest Z Lite Sol accordéon orange léger', 4.6, 456,
 true, 'achat', 'P077', '183×51×2 cm', 'Mousse EVA', '2 ans constructeur',
 'Le Z Lite Sol est le matelas mousse de référence. Indestructible, léger et abordable, il ne peut pas crever et convient à toutes les conditions.',
 '["Indestructible","Léger","Prix abordable","R-value 2"]'::jsonb,
 '["Moins confortable que gonflable","Encombrant","R-value limité"]'::jsonb,
 NULL, 'P009', true, true,
 7.5, 10.0, 10.0, 'OutdoorGearLab 2025',
 75, 'Recommandé', 8.0, false,
 10.0, '["Trek","Camping","Backpacking"]'::jsonb, '["Tempéré","Montagne"]'::jsonb,
 'Le matelas indestructible. Parfait pour les conditions difficiles ou comme backup.'),

('sea-to-summit-spark-sp3', 'Sea to Summit Spark SP3', 'Sea to Summit', 'Spark SP3', 'Couchage', 'Couchage', 'Sacs de couchage',
 780, 780, 449.00, 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=600&q=80', 'Sac de couchage Sea to Summit Spark SP3 bleu 3 saisons léger', 4.8, 134,
 true, 'achat', 'P078', '25×15 cm (compressé)', 'Duvet 850+ cuin', '2 ans constructeur',
 'Le Spark SP3 est la version 3 saisons du Spark SP1. Son confort à -9°C et son poids de 780g en font le sac de couchage polyvalent par excellence.',
 '["Confort -9°C","Léger","Duvet 850+ cuin","Polyvalent"]'::jsonb,
 '["Prix élevé","Sensible à l''humidité"]'::jsonb,
 'P008', 'P007', true, true,
 9.0, 6.5, 8.5, 'OutdoorGearLab 2025',
 86, 'Recommandé', 8.5, false,
 7.0, '["Trek","Backpacking","Expédition 3 saisons"]'::jsonb, '["Montagne","Tempéré","Arctique léger"]'::jsonb,
 'Le sac de couchage 3 saisons de référence. Polyvalent et léger.'),

('msr-dromedary-bag-10l', 'MSR Dromedary Bag 10L', 'MSR', 'Dromedary Bag 10L', 'Eau', 'Eau', 'Réservoirs',
 170, 170, 35.00, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80', 'Réservoir eau MSR Dromedary Bag 10 litres bleu camp de base', 4.7, 145,
 true, 'achat', 'P079', '10L capacité', 'Polyuréthane sans BPA', '2 ans constructeur',
 'Le Dromedary Bag est le réservoir d''eau de camp de base de référence. Sa robustesse et sa grande capacité en font le choix des expéditions et des camps de base.',
 '["Robuste","Grande capacité","Polyvalent","Facile à remplir"]'::jsonb,
 '["Lourd plein","Pas pour randonnée","Encombrant"]'::jsonb,
 NULL, 'P043', true, true,
 8.5, 9.0, 9.0, 'MSR Official 2025',
 72, 'Recommandé', 6.0, false,
 8.5, '["Camp de base","Expédition","Camping"]'::jsonb, '["Tous"]'::jsonb,
 'Indispensable pour les camps de base. Stockage eau fiable et robuste.'),

('black-diamond-cosmo-350', 'Black Diamond Cosmo 350', 'Black Diamond', 'Cosmo 350', 'Éclairage', 'Éclairage', 'Frontales',
 95, 95, 45.00, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', 'Lampe frontale Black Diamond Cosmo 350 lumens rechargeable USB', 4.6, 189,
 true, 'achat', 'P080', '7×4×3 cm', 'ABS', '3 ans constructeur',
 'La Cosmo 350 est la frontale rechargeable polyvalente de Black Diamond. Ses 350 lumens et sa recharge USB en font un excellent choix pour les randonneurs modernes.',
 '["Rechargeable USB","350 lumens","Légère","Mode rouge"]'::jsonb,
 '["Moins puissante que NAO","Batterie non remplaçable"]'::jsonb,
 'P011', 'P073', true, true,
 8.0, 9.0, 8.0, 'Black Diamond Official 2025',
 76, 'Recommandé', 8.5, true,
 8.0, '["Randonnée","Camping","Trek"]'::jsonb, '["Tous"]'::jsonb,
 'Bon choix rechargeable à prix abordable. Alternative à la Petzl Actik.'),

('salomon-xa-pro-3d-v8', 'Salomon XA Pro 3D V8', 'Salomon', 'XA Pro 3D V8', 'Chaussures', 'Chaussures', 'Chaussures de randonnée',
 720, 720, 139.00, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', 'Chaussures randonnée Salomon XA Pro 3D V8 grises imperméables robustes', 4.6, 456,
 true, 'achat', 'P081', '36-48', 'Gore-Tex, Contagrip MA', '2 ans constructeur',
 'Les XA Pro 3D V8 sont les chaussures de randonnée robustes de Salomon. Leur protection 3D Advanced Chassis et leur semelle Contagrip MA en font un choix fiable pour les terrains difficiles.',
 '["Très robustes","Gore-Tex","Protection 3D","Polyvalentes"]'::jsonb,
 '["Plus lourdes que X Ultra","Moins légères"]'::jsonb,
 'P024', NULL, true, true,
 8.5, 8.5, 9.0, 'OutdoorGearLab 2025',
 82, 'Recommandé', 8.5, false,
 8.5, '["Trek","Randonnée","Backpacking"]'::jsonb, '["Montagne","Tempéré","Pluvieux"]'::jsonb,
 'Excellent choix pour les terrains difficiles. Plus robuste que X Ultra.')

ON CONFLICT (slug) DO UPDATE SET
  product_id = EXCLUDED.product_id,
  model = EXCLUDED.model,
  category_main = EXCLUDED.category_main,
  category_sub = EXCLUDED.category_sub,
  weight_grams = EXCLUDED.weight_grams,
  dimensions = EXCLUDED.dimensions,
  materials = EXCLUDED.materials,
  warranty = EXCLUDED.warranty,
  description_why = EXCLUDED.description_why,
  advantages_array = EXCLUDED.advantages_array,
  disadvantages_array = EXCLUDED.disadvantages_array,
  alt_premium_id = EXCLUDED.alt_premium_id,
  alt_budget_id = EXCLUDED.alt_budget_id,
  available_europe = EXCLUDED.available_europe,
  available_usa = EXCLUDED.available_usa,
  score_quality = EXCLUDED.score_quality,
  score_price = EXCLUDED.score_price,
  score_durability = EXCLUDED.score_durability,
  source_review = EXCLUDED.source_review,
  score_kdv = EXCLUDED.score_kdv,
  essentiality = EXCLUDED.essentiality,
  versatility_10 = EXCLUDED.versatility_10,
  cabin_compatible = EXCLUDED.cabin_compatible,
  repairability_10 = EXCLUDED.repairability_10,
  travel_types_array = EXCLUDED.travel_types_array,
  climates_array = EXCLUDED.climates_array,
  justification_ai = EXCLUDED.justification_ai,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  weight_g = EXCLUDED.weight_g,
  price_eur = EXCLUDED.price_eur,
  image = EXCLUDED.image,
  image_alt = EXCLUDED.image_alt,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  updated_at = NOW();

-- ── 6. Compatibilités (feuille 07) ───────────────────────────────────────────

INSERT INTO public.product_compatibilities (product_id_1, product_id_2, relation_type, notes) VALUES
('P001', 'P051', 'compatible_with', 'Daylite Plus se fixe sur Farpoint 40'),
('P004', 'P007', 'completes', 'Tente + sac de couchage = kit nuit complet'),
('P004', 'P009', 'completes', 'Tente + matelas = kit nuit complet'),
('P007', 'P009', 'completes', 'Sac de couchage + matelas = système de couchage'),
('P007', 'P065', 'completes', 'Sac de couchage + oreiller = confort nuit'),
('P011', 'P033', 'compatible_with', 'Frontale rechargeable + batterie externe'),
('P014', 'P043', 'compatible_with', 'Filtre BeFree + gourde Hydrapak'),
('P017', 'P018', 'completes', 'inReach Mini + GPS = navigation complète'),
('P027', 'P049', 'compatible_with', 'WindBurner + PocketRocket = système cuisine complet'),
('P027', 'P070', 'compatible_with', 'Réchaud MSR + casserole MSR'),
('P001', 'P037', 'requires', 'Sac à dos + housse de pluie'),
('P003', 'P037', 'requires', 'Sac à dos + housse de pluie'),
('P020', 'P041', 'completes', 'Veste imperméable + doudoune = système couches'),
('P022', 'P020', 'completes', 'Sous-vêtement mérinos + veste imperméable'),
('P024', 'P038', 'completes', 'Chaussures randonnée + bâtons'),
('P030', 'P061', 'completes', 'Trousse secours + pastilles purification'),
('P033', 'P035', 'compatible_with', 'Batterie externe + panneau solaire'),
('P004', 'P066', 'completes', 'Tente + drap de voyage = kit nuit complet'),
('P001', 'P036', 'requires', 'Sac à dos + sac étanche pour électronique'),
('P062', 'P017', 'compatible_with', 'Montre GPS + communicateur satellite'),
('P074', 'P001', 'compatible_with', 'Poche à eau compatible sacs Osprey'),
('P074', 'P003', 'compatible_with', 'Poche à eau compatible sacs Gregory'),
('P032', 'P053', 'requires', 'Grigri + baudrier = système assurage'),
('P053', 'P055', 'completes', 'Baudrier + casque = kit escalade sécurité'),
('P019', 'P062', 'compatible_with', 'Suunto + Garmin = double navigation'),
('P040', 'P022', 'completes', 'Buff + mérinos = système thermique tête/corps'),
('P046', 'P024', 'completes', 'Short + chaussures = tenue randonnée légère'),
('P068', 'P036', 'compatible_with', 'Deux sacs étanches pour organisation'),
('P079', 'P014', 'completes', 'Réservoir camp + filtre = système eau camp'),
('P077', 'P007', 'completes', 'Matelas mousse + sac de couchage = kit nuit robuste')
ON CONFLICT (id) DO NOTHING;

-- ── 7. Alternatives (feuille 08) ─────────────────────────────────────────────

INSERT INTO public.product_alternatives (original_product_id, substitute_product_id, priority, reason) VALUES
('P001', 'P052', 1, 'Sac de voyage polyvalent si pas de trek technique'),
('P001', 'P059', 2, 'Version ultraléger pliable pour voyageurs minimalistes'),
('P004', 'P076', 1, 'Version abordable pour débutants'),
('P004', 'P075', 2, 'Version ultraléger pour randonneurs solo'),
('P007', 'P078', 1, 'Version 3 saisons plus polyvalente'),
('P009', 'P077', 1, 'Version indestructible mousse si budget limité'),
('P009', 'P010', 2, 'Version ultraléger si poids prioritaire'),
('P011', 'P073', 1, 'Version économique rechargeable'),
('P011', 'P069', 2, 'Version budget piles standard'),
('P014', 'P015', 1, 'Alternative légère et abordable'),
('P014', 'P060', 2, 'Version ultra-budget pour backup'),
('P017', 'P019', 1, 'Montre GPS si navigation moins critique'),
('P020', 'P021', 1, 'Version éco-responsable moins chère'),
('P022', 'P023', 1, 'Version légère pour climat chaud'),
('P022', 'P067', 2, 'Version synthétique éco-responsable'),
('P024', 'P025', 1, 'Version trail running si terrain sec'),
('P027', 'P028', 1, 'Jetboil si rapidité prioritaire'),
('P027', 'P049', 2, 'PocketRocket si légèreté prioritaire'),
('P033', 'P034', 1, 'Version compacte si cabine avion'),
('P041', 'P057', 1, 'Alternative duvet naturel'),
('P041', 'P042', 2, 'Version premium Arc''teryx'),
('P038', 'P039', 1, 'Version carbone pliable premium'),
('P038', 'P045', 2, 'Version trail running'),
('P036', 'P068', 1, 'Version plus robuste si usage intensif'),
('P062', 'P019', 1, 'Suunto si préférence interface'),
('P004', 'P006', 1, 'Version ultraléger NEMO si poids critique')
ON CONFLICT (id) DO NOTHING;

-- ── 8. Vérification finale ────────────────────────────────────────────────────

DO $$
DECLARE
  product_count INTEGER;
  compat_count INTEGER;
  alt_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO product_count FROM public.shop_products WHERE product_id IS NOT NULL;
  SELECT COUNT(*) INTO compat_count FROM public.product_compatibilities;
  SELECT COUNT(*) INTO alt_count FROM public.product_alternatives;
  RAISE NOTICE 'Import terminé: % produits, % compatibilités, % alternatives', product_count, compat_count, alt_count;
END $$;
