-- ============================================================================
-- Catalogue d'activités — seed initial réellement exploitable par /prepare
--
-- public.activities n'est pas touchée : elle reste l'historique des sessions.
-- Ce seed décrit 43 formats d'activités, du footing court au road trip long.
-- Les valeurs par défaut sont explicites ; aucune donnée n'est générée à l'affichage.
-- ============================================================================

BEGIN;

WITH catalog_seed(
  slug,
  label,
  family,
  description,
  logistics_scope,
  sport_tags,
  duration_minutes,
  distance_km,
  elevation_gain_m,
  technicality,
  stage_count,
  day_count,
  budget_eur
) AS (
  VALUES
    (
      'footing-45',
      'Footing 45 minutes',
      'running',
      'Course courte démarrant et revenant au même point.',
      'none'::public.activity_logistics_scope,
      ARRAY['course', 'footing', 'urbain'],
      45,
      7,
      30,
      1,
      NULL,
      NULL,
      NULL
    ),
    (
      'footing-90',
      'Footing 90 minutes',
      'running',
      'Course continue d’une heure et demie.',
      'none'::public.activity_logistics_scope,
      ARRAY['course', 'footing', 'endurance'],
      90,
      15,
      80,
      1,
      NULL,
      NULL,
      NULL
    ),
    (
      'course-5k',
      'Course 5 km',
      'running',
      'Course courte chronométrée ou loosening.',
      'none'::public.activity_logistics_scope,
      ARRAY['course', '5k', 'competition'],
      35,
      5,
      20,
      1,
      NULL,
      NULL,
      NULL
    ),
    (
      'trail-10k',
      'Trail 10 km',
      'running',
      'Course trail avec dénivelé et passages techniques.',
      'access'::public.activity_logistics_scope,
      ARRAY['trail', 'course', 'montagne'],
      75,
      10,
      450,
      3,
      NULL,
      NULL,
      NULL
    ),
    (
      'trail-ultra-65k',
      'Trail ultra 65 km',
      'running',
      'EffortSupported long avec ravitaillement, eau et secours.',
      'access'::public.activity_logistics_scope,
      ARRAY['trail', 'ultra', 'long'],
      780,
      65,
      4500,
      5,
      NULL,
      2,
      140
    ),
    (
      'rando-matin',
      'Randonnée du matin',
      'hiking',
      'Sortie rando courte, souvent avant midi.',
      'access'::public.activity_logistics_scope,
      ARRAY['randonnée', 'demi-journée', 'nature'],
      210,
      11,
      420,
      2,
      NULL,
      NULL,
      NULL
    ),
    (
      'rando-journee',
      'Randonnée à la journée',
      'hiking',
      'Boucle ou aller-retour hikes sur une journée.',
      'access'::public.activity_logistics_scope,
      ARRAY['randonnée', 'journée', 'montagne'],
      390,
      16,
      780,
      3,
      NULL,
      NULL,
      NULL
    ),
    (
      'rando-refuge',
      'Randonnée avec refuge',
      'hiking',
      'Rando avec nuit en refuge ou gîte d’étape.',
      'access'::public.activity_logistics_scope,
      ARRAY['randonnée', 'refuge', 'journée'],
      300,
      13,
      900,
      3,
      NULL,
      NULL,
      NULL
    ),
    (
      'rando-famille',
      'Randonnée famille',
      'hiking',
      'Parcours progressif, court et adapté aux enfants.',
      'access'::public.activity_logistics_scope,
      ARRAY['randonnée', 'famille', 'accessible'],
      150,
      6,
      180,
      1,
      NULL,
      NULL,
      NULL
    ),
    (
      'trekking-2j',
      'Trekking deux jours',
      'hiking',
      'Deux étapes de randonnée avec nuit en bivouac ou gîte.',
      'stages'::public.activity_logistics_scope,
      ARRAY['trekking', 'multi-jours', 'étape'],
      900,
      28,
      1500,
      3,
      2,
      2,
      NULL
    ),
    (
      'rando-camping',
      'Rando camping',
      'hiking',
      'Rando avec campement installé près du refuge.',
      'stages'::public.activity_logistics_scope,
      ARRAY['randonnée', 'camping', 'nuit'],
      660,
      22,
      1200,
      3,
      1,
      2,
      NULL
    ),
    (
      'bivouac-1n',
      'Bivouac une nuit',
      'bivouac',
      'Sortie avec un seul bivouac et retour au départ.',
      'access'::public.activity_logistics_scope,
      ARRAY['bivouac', 'nuit', 'montagne'],
      780,
      24,
      1600,
      4,
      1,
      2,
      NULL
    ),
    (
      'bivouac-2n',
      'Bivouac deux nuits',
      'bivouac',
      'Itinéraire autonome avec deux nuits en bivouac.',
      'stages'::public.activity_logistics_scope,
      ARRAY['bivouac', 'multi-jours', 'autonomie'],
      1440,
      44,
      3100,
      4,
      2,
      3,
      NULL
    ),
    (
      'bivouac-3j',
      'Bivouac trois jours',
      'bivouac',
      'Trois jours de portage et bivouac sur un trajet de longue distance.',
      'stages'::public.activity_logistics_scope,
      ARRAY['bivouac', 'portage', 'multi-jours'],
      2520,
      72,
      5600,
      5,
      3,
      4,
      NULL
    ),
    (
      'trek-4j',
      'Trek quatre jours',
      'bivouac',
      'Voyage de quatre jours avec étapes et nuitées adaptées.',
      'stages'::public.activity_logistics_scope,
      ARRAY['trek', 'multi-jours', 'étape'],
      2880,
      82,
      6400,
      4,
      4,
      5,
      NULL
    ),
    (
      'traverse-5j',
      'Grande traversée cinq jours',
      'bivouac',
      'Traversée longue avec gestion de l’eau, des abris et des réserves.',
      'stages'::public.activity_logistics_scope,
      ARRAY['traversée', 'autonomie', 'multi-jours'],
      3600,
      105,
      7800,
      5,
      5,
      6,
      NULL
    ),
    (
      'roadtrip-europe',
      'Road trip Europe',
      'roadtrip',
      'Circuit en voiture à travers plusieurs pays européens.',
      'full'::public.activity_logistics_scope,
      ARRAY['road trip', 'voiture', 'europe'],
      NULL,
      3200,
      NULL,
      2,
      6,
      14,
      2400
    ),
    (
      'roadtrip-amerique-sud',
      'Road trip Amérique du Sud',
      'roadtrip',
      'Voyage routière longue en Amérique du Sud avec vols, voitures et hôtels.',
      'full'::public.activity_logistics_scope,
      ARRAY['road trip', 'voiture', 'amérique du sud'],
      NULL,
      8000,
      NULL,
      3,
      12,
      45,
      7500
    ),
    (
      'roadtrip-islandes',
      'Road trip Islande',
      'roadtrip',
      'Boucle routière nordique avec ajustement de l’itinéraire et météo variable.',
      'full'::public.activity_logistics_scope,
      ARRAY['road trip', 'voiture', 'islande'],
      NULL,
      1332,
      NULL,
      2,
      7,
      10,
      3200
    ),
    (
      'roadtrip-national',
      'Road trip national',
      'roadtrip',
      'Boucle ou traverse dans un pays, avec escales et nuitées.',
      'full'::public.activity_logistics_scope,
      ARRAY['road trip', 'voiture', 'national'],
      NULL,
      1800,
      NULL,
      2,
      5,
      12,
      1800
    ),
    (
      'roadtrip-desert',
      'Road trip désert',
      'roadtrip',
      'Voyage saharien ou désertique avec longues distances et forte préparation.',
      'full'::public.activity_logistics_scope,
      ARRAY['road trip', 'voiture', 'désert'],
      NULL,
      2400,
      NULL,
      4,
      6,
      10,
      4100
    ),
    (
      'city-break-48h',
      'Escapade ville 48 h',
      'city',
      'Court séjour urbain avec transport, hébergement et activités.',
      'access'::public.activity_logistics_scope,
      ARRAY['ville', 'week-end', 'culture'],
      2880,
      NULL,
      NULL,
      1,
      1,
      2,
      420
    ),
    (
      'city-break-72h',
      'Séjour ville 72 h',
      'city',
      'Trois jours de découverte urbaine et culturelle.',
      'access'::public.activity_logistics_scope,
      ARRAY['ville', 'séjour', 'culture'],
      4320,
      NULL,
      NULL,
      1,
      1,
      3,
      680
    ),
    (
      'visite-culturelle',
      'Visite culturelle guidée',
      'culture',
      'Visite de musée, monument ou quartier avec réservation.',
      'access'::public.activity_logistics_scope,
      ARRAY['culture', 'musée', 'visite'],
      120,
      NULL,
      NULL,
      1,
      NULL,
      NULL,
      35
    ),
    (
      'musee-journee',
      'Musée et journée culturelle',
      'culture',
      'Journée consacrée à la culture, aux musées et aux quartiers historiques.',
      'access'::public.activity_logistics_scope,
      ARRAY['musée', 'culture', 'journée'],
      420,
      NULL,
      NULL,
      1,
      NULL,
      NULL,
      55
    ),
    (
      'gastronomie-tour',
      'Tour gastronomique',
      'gastronomy',
      'Découverte de producteurs, marchés et restaurants.',
      'access'::public.activity_logistics_scope,
      ARRAY['gastronomie', 'marché', 'producteurs'],
      240,
      NULL,
      NULL,
      1,
      NULL,
      NULL,
      95
    ),
    (
      'canoe-journee',
      'Canoë à la journée',
      'water',
      'Sortie de canoë avec équipement, embarquement et retour.',
      'access'::public.activity_logistics_scope,
      ARRAY['canoë', 'eau', 'journée'],
      330,
      18,
      NULL,
      2,
      NULL,
      NULL,
      65
    ),
    (
      'sailing-week',
      'Croisière voile une semaine',
      'water',
      'Navigation avec skipper, couchages et ports d’étape.',
      'stages'::public.activity_logistics_scope,
      ARRAY['voile', 'croisière', 'hebdomadaire'],
      9000,
      180,
      NULL,
      2,
      5,
      7,
      950
    ),
    (
      'plongee-autonome',
      'Plongée autonome',
      'water',
      'Séance de plongée avec certification et équipement.',
      'access'::public.activity_logistics_scope,
      ARRAY['plongée', 'eau', 'certification'],
      240,
      NULL,
      NULL,
      3,
      NULL,
      NULL,
      190
    ),
    (
      'surf-session',
      'Session de surf',
      'water',
      'Session de surf avec instructeur et matériel.',
      'access'::public.activity_logistics_scope,
      ARRAY['surf', 'océan', 'initiation'],
      150,
      NULL,
      NULL,
      2,
      NULL,
      NULL,
      75
    ),
    (
      'river-camping',
      'Camping rivière',
      'water',
      'Camping multi-jours le long d’une rivière.',
      'stages'::public.activity_logistics_scope,
      ARRAY['camping', 'rivière', 'multi-jours'],
      720,
      32,
      220,
      2,
      2,
      3,
      120
    ),
    (
      'ski-randonnee',
      'Ski de randonnée',
      'winter',
      'Ascension puis descente à ski en dehors des pistes.',
      'full'::public.activity_logistics_scope,
      ARRAY['ski', 'montagne', 'hiver'],
      420,
      18,
      1100,
      4,
      1,
      2,
      260
    ),
    (
      'snowboard-sejour',
      'Séjour snowboard',
      'winter',
      'Séjour de board avec station, Equipment et lodging.',
      'full'::public.activity_logistics_scope,
      ARRAY['snowboard', 'hiver', 'station'],
      20160,
      NULL,
      NULL,
      2,
      1,
      7,
      780
    ),
    (
      'raquettes-journee',
      'Raquettes à la journée',
      'winter',
      'Sortie en raquettes avec guide et matériel.',
      'access'::public.activity_logistics_scope,
      ARRAY['raquettes', 'neige', 'journée'],
      300,
      8,
      320,
      2,
      NULL,
      NULL,
      85
    ),
    (
      'velo-route',
      'Vélo route',
      'cycling',
      'Sortie vélo sur route avec transport et repair kit.',
      'access'::public.activity_logistics_scope,
      ARRAY['vélo', 'route', 'journée'],
      330,
      62,
      700,
      2,
      NULL,
      NULL,
      60
    ),
    (
      'gravel-bivouac',
      'Gravel et bivouac',
      'cycling',
      'Deux jours en gravel avec bivouac et réparation.',
      'stages'::public.activity_logistics_scope,
      ARRAY['gravel', 'vélo', 'bivouac'],
      1800,
      110,
      1600,
      3,
      2,
      3,
      180
    ),
    (
      'bikepacking-3j',
      'Bikepacking trois jours',
      'cycling',
      'Trois jours à vélo avec bagage léger et nuitées.',
      'stages'::public.activity_logistics_scope,
      ARRAY['bikepacking', 'vélo', 'multi-jours'],
      2700,
      160,
      2400,
      3,
      3,
      4,
      240
    ),
    (
      'wingfoil-initiation',
      'Initiation wingfoil',
      'air',
      'Découverte du wingfoil avec instructeur et matériel.',
      'access'::public.activity_logistics_scope,
      ARRAY['wingfoil', 'eau', 'initiation'],
      180,
      NULL,
      NULL,
      2,
      NULL,
      NULL,
      130
    ),
    (
      'tandem-parapente',
      'Vol en parapente',
      'air',
      'Vol tandem encadré avec ascent et aterrizage.',
      'access'::public.activity_logistics_scope,
      ARRAY['parapente', 'vol', 'tandem'],
      120,
      NULL,
      NULL,
      2,
      NULL,
      NULL,
      145
    ),
    (
      'kayak-sea',
      'Kayak en mer',
      'water',
      'Sortie en kayak de mer avec équipement et navigation.',
      'access'::public.activity_logistics_scope,
      ARRAY['kayak', 'mer', 'navigation'],
      240,
      12,
      NULL,
      2,
      NULL,
      NULL,
      110
    ),
    (
      'scooter-ile',
      'Scooter sur une île',
      'motor',
      'Loop à scooter sur une île avec hébergement et carburant.',
      'full'::public.activity_logistics_scope,
      ARRAY['scooter', 'île', 'moto'],
      20160,
      420,
      NULL,
      2,
      1,
      7,
      520
    ),
    (
      'van-life-3j',
      'Van life trois jours',
      'motor',
      'Trois jours en van avec spots, énergie et approvisionnement.',
      'stages'::public.activity_logistics_scope,
      ARRAY['van', 'road trip', 'camping'],
      4320,
      260,
      600,
      2,
      3,
      4,
      160
    ),
    (
      'moto-roadtrip',
      'Road trip moto',
      'motor',
      'Traversée moto avec étapes, carburant et hébergements.',
      'full'::public.activity_logistics_scope,
      ARRAY['moto', 'road trip', 'longue distance'],
      14400,
      3200,
      NULL,
      3,
      8,
      18,
      2800
    )
)
INSERT INTO public.activity_catalog (
  slug,
  label,
  family,
  description,
  logistics_scope,
  sport_tags,
  metrics,
  is_seed,
  is_active
)
SELECT
  slug,
  label,
  family,
  description,
  logistics_scope,
  sport_tags,
  jsonb_strip_nulls(
    jsonb_build_object(
      'duration_minutes', duration_minutes,
      'distance_km', distance_km,
      'elevation_gain_m', elevation_gain_m,
      'technicality', technicality,
      'stage_count', stage_count,
      'day_count', day_count,
      'budget_eur', budget_eur
    )
  ),
  true,
  true
FROM catalog_seed
ON CONFLICT (slug) DO UPDATE
SET
  label = EXCLUDED.label,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  logistics_scope = EXCLUDED.logistics_scope,
  sport_tags = EXCLUDED.sport_tags,
  metrics = EXCLUDED.metrics,
  is_seed = true,
  is_active = true,
  updated_at = now();

WITH catalog_seed(
  slug,
  duration_minutes,
  distance_km,
  elevation_gain_m,
  technicality,
  stage_count,
  day_count,
  budget_eur
) AS (
  VALUES
    ('footing-45', 45, 7, 30, 1, NULL, NULL, NULL),
    ('footing-90', 90, 15, 80, 1, NULL, NULL, NULL),
    ('course-5k', 35, 5, 20, 1, NULL, NULL, NULL),
    ('trail-10k', 75, 10, 450, 3, NULL, NULL, NULL),
    ('trail-ultra-65k', 780, 65, 4500, 5, NULL, 2, 140),
    ('rando-matin', 210, 11, 420, 2, NULL, NULL, NULL),
    ('rando-journee', 390, 16, 780, 3, NULL, NULL, NULL),
    ('rando-refuge', 300, 13, 900, 3, NULL, NULL, NULL),
    ('rando-famille', 150, 6, 180, 1, NULL, NULL, NULL),
    ('trekking-2j', 900, 28, 1500, 3, 2, 2, NULL),
    ('rando-camping', 660, 22, 1200, 3, 1, 2, NULL),
    ('bivouac-1n', 780, 24, 1600, 4, 1, 2, NULL),
    ('bivouac-2n', 1440, 44, 3100, 4, 2, 3, NULL),
    ('bivouac-3j', 2520, 72, 5600, 5, 3, 4, NULL),
    ('trek-4j', 2880, 82, 6400, 4, 4, 5, NULL),
    ('traverse-5j', 3600, 105, 7800, 5, 5, 6, NULL),
    ('roadtrip-europe', NULL, 3200, NULL, 2, 6, 14, 2400),
    ('roadtrip-amerique-sud', NULL, 8000, NULL, 3, 12, 45, 7500),
    ('roadtrip-islandes', NULL, 1332, NULL, 2, 7, 10, 3200),
    ('roadtrip-national', NULL, 1800, NULL, 2, 5, 12, 1800),
    ('roadtrip-desert', NULL, 2400, NULL, 4, 6, 10, 4100),
    ('city-break-48h', 2880, NULL, NULL, 1, 1, 2, 420),
    ('city-break-72h', 4320, NULL, NULL, 1, 1, 3, 680),
    ('visite-culturelle', 120, NULL, NULL, 1, NULL, NULL, 35),
    ('musee-journee', 420, NULL, NULL, 1, NULL, NULL, 55),
    ('gastronomie-tour', 240, NULL, NULL, 1, NULL, NULL, 95),
    ('canoe-journee', 330, 18, NULL, 2, NULL, NULL, 65),
    ('sailing-week', 9000, 180, NULL, 2, 5, 7, 950),
    ('plongee-autonome', 240, NULL, NULL, 3, NULL, NULL, 190),
    ('surf-session', 150, NULL, NULL, 2, NULL, NULL, 75),
    ('river-camping', 720, 32, 220, 2, 2, 3, 120),
    ('ski-randonnee', 420, 18, 1100, 4, 1, 2, 260),
    ('snowboard-sejour', 20160, NULL, NULL, 2, 1, 7, 780),
    ('raquettes-journee', 300, 8, 320, 2, NULL, NULL, 85),
    ('velo-route', 330, 62, 700, 2, NULL, NULL, 60),
    ('gravel-bivouac', 1800, 110, 1600, 3, 2, 3, 180),
    ('bikepacking-3j', 2700, 160, 2400, 3, 3, 4, 240),
    ('wingfoil-initiation', 180, NULL, NULL, 2, NULL, NULL, 130),
    ('tandem-parapente', 120, NULL, NULL, 2, NULL, NULL, 145),
    ('kayak-sea', 240, 12, NULL, 2, NULL, NULL, 110),
    ('scooter-ile', 20160, 420, NULL, 2, 1, 7, 520),
    ('van-life-3j', 4320, 260, 600, 2, 3, 4, 160),
    ('moto-roadtrip', 14400, 3200, NULL, 3, 8, 18, 2800)
)
INSERT INTO public.activity_catalog_metrics (
  activity_id,
  metric_key,
  label,
  unit,
  value_kind,
  required,
  default_value,
  min_value,
  max_value,
  weight,
  position,
  help_text
)
SELECT
  catalog.id,
  metric.metric_key,
  metric.label,
  metric.unit,
  metric.value_kind,
  metric.required,
  metric.default_value,
  metric.min_value,
  metric.max_value,
  metric.weight,
  metric.position,
  metric.help_text
FROM catalog_seed seed
JOIN public.activity_catalog catalog ON catalog.slug = seed.slug
CROSS JOIN LATERAL (
  VALUES
    (
      CASE WHEN seed.duration_minutes IS NOT NULL
        THEN 'duration_minutes'::text ELSE NULL END,
      'Durée',
      'min',
      'duration'::public.activity_metric_kind,
      seed.duration_minutes IS NOT NULL,
      seed.duration_minutes,
      5::numeric,
      20160::numeric,
      10,
      10,
      'Durée hors pauses et trajets.'
    ),
    (
      CASE WHEN seed.distance_km IS NOT NULL
        THEN 'distance_km'::text ELSE NULL END,
      'Distance',
      'km',
      'distance'::public.activity_metric_kind,
      seed.distance_km IS NOT NULL,
      seed.distance_km,
      0::numeric,
      50000::numeric,
      10,
      20,
      'Distance totale de l’itinéraire.'
    ),
    (
      CASE WHEN seed.elevation_gain_m IS NOT NULL
        THEN 'elevation_gain_m'::text ELSE NULL END,
      'Dénivelé positif',
      'm',
      'elevation'::public.activity_metric_kind,
      seed.elevation_gain_m IS NOT NULL,
      seed.elevation_gain_m,
      0::numeric,
      30000::numeric,
      8,
      30,
      'Dénivelé cumulé sur l’itinéraire.'
    ),
    (
      CASE WHEN seed.technicality IS NOT NULL
        THEN 'technicality'::text ELSE NULL END,
      'Technicité',
      '/5',
      'technicity'::public.activity_metric_kind,
      seed.technicality IS NOT NULL,
      seed.technicality,
      1::numeric,
      5::numeric,
      6,
      40,
      'Niveau global de technicité et de risque.'
    ),
    (
      CASE WHEN seed.stage_count IS NOT NULL
        THEN 'stage_count'::text ELSE NULL END,
      'Nombre d’étapes',
      'étapes',
      'number'::public.activity_metric_kind,
      seed.stage_count IS NOT NULL,
      seed.stage_count,
      1::numeric,
      60::numeric,
      7,
      50,
      'Nombre d’étapes de préparation.'
    ),
    (
      CASE WHEN seed.day_count IS NOT NULL
        THEN 'day_count'::text ELSE NULL END,
      'Durée du séjour',
      'jours',
      'days'::public.activity_metric_kind,
      seed.day_count IS NOT NULL,
      seed.day_count,
      1::numeric,
      365::numeric,
      9,
      60,
      'Nombre de jours sur place.'
    ),
    (
      CASE WHEN seed.budget_eur IS NOT NULL
        THEN 'budget_eur'::text ELSE NULL END,
      'Budget cible',
      '€',
      'budget'::public.activity_metric_kind,
      seed.budget_eur IS NOT NULL,
      seed.budget_eur,
      0::numeric,
      250000::numeric,
      8,
      70,
      'Budget de préparation hors achats déjà validés.'
    )
) AS metric(
  metric_key,
  label,
  unit,
  value_kind,
  required,
  default_value,
  min_value,
  max_value,
  weight,
  position,
  help_text
)
WHERE metric.metric_key IS NOT NULL
ON CONFLICT (activity_id, metric_key) DO UPDATE
SET
  label = EXCLUDED.label,
  unit = EXCLUDED.unit,
  value_kind = EXCLUDED.value_kind,
  required = EXCLUDED.required,
  default_value = EXCLUDED.default_value,
  min_value = EXCLUDED.min_value,
  max_value = EXCLUDED.max_value,
  weight = EXCLUDED.weight,
  position = EXCLUDED.position,
  help_text = EXCLUDED.help_text,
  updated_at = now();

COMMIT;
